blank_lines_lower_bound = 1
color = "always"
combine_control_expr = false
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
imports_layout = "Vertical"
max_width = 80
merge_imports = true
newline_style = "Unix"
reorder_impl_items = true
unstable_features = true
wrap_comments = true
