use crate::enums::{
  BlockType,
  WallType,
};
use image::Rgba;
use std::collections::HashMap;

pub const ABBEY: Rgba<i32> = Rgba([76, 74, 83, 255]);
pub const AFFAIR: Rgba<i32> = Rgba([113, 64, 150, 255]);
pub const ALIZARIN_CRIMSON: Rgba<i32> = Rgba([231, 53, 56, 255]);
pub const AMETHYST_SMOKE: Rgba<i32> = Rgba([147, 144, 178, 255]);
pub const AMULET: Rgba<i32> = Rgba([132, 157, 127, 255]);
pub const ANTIQUE_BRASS: Rgba<i32> = Rgba([191, 142, 111, 255]);
pub const APPLE: Rgba<i32> = Rgba([23, 177, 76, 255]);
pub const ARMADILLO: Rgba<i32> = Rgba([62, 61, 52, 255]);
pub const ASH: Rgba<i32> = Rgba([190, 190, 178, 255]);
pub const ASTRONAUT: Rgba<i32> = Rgba([23, 54, 119, 255]);
pub const ATHENS_GRAY: Rgba<i32> = Rgba([240, 240, 247, 255]);
pub const ATLANTIS: Rgba<i32> = Rgba([143, 215, 29, 255]);
pub const AUBERGINE: Rgba<i32> = Rgba([61, 13, 16, 255]);
pub const AU_CHICO: Rgba<i32> = Rgba([145, 81, 85, 255]);
pub const AVOCADO: Rgba<i32> = Rgba([157, 157, 107, 255]);
pub const AXOLOTL: Rgba<i32> = Rgba([84, 100, 63, 255]);
pub const AZURE: Rgba<i32> = Rgba([39, 94, 168, 255]);
pub const AZURE_RADIANCE: Rgba<i32> = Rgba([93, 127, 255, 255]);
pub const BABY_BLUE: Rgba<i32> = Rgba([223, 255, 255, 255]);
pub const BALI_HAI: Rgba<i32> = Rgba([141, 163, 181, 255]);
pub const BALTIC_SEA: Rgba<i32> = Rgba([44, 41, 50, 255]);
pub const BASTILLE: Rgba<i32> = Rgba([41, 28, 36, 255]);
pub const BEAVER: Rgba<i32> = Rgba([140, 101, 80, 255]);
pub const BIG_STONE: Rgba<i32> = Rgba([11, 35, 62, 255]);
pub const BISCAY: Rgba<i32> = Rgba([51, 47, 96, 255]);
pub const BISTRE: Rgba<i32> = Rgba([55, 39, 26, 255]);
pub const BIZARRE: Rgba<i32> = Rgba([238, 225, 218, 255]);
pub const BLACK: Rgba<i32> = Rgba([0, 0, 0, 0]);
pub const BLACK_MARLIN: Rgba<i32> = Rgba([59, 39, 22, 255]);
pub const BLACK_ROSE: Rgba<i32> = Rgba([117, 32, 59, 255]);
pub const BLEACHED_CEDAR: Rgba<i32> = Rgba([48, 35, 52, 255]);
pub const BLUE: Rgba<i32> = Rgba([0, 12, 255, 128]);
pub const BLUE_BELL: Rgba<i32> = Rgba([151, 135, 183, 255]);
pub const BLUE_DIANNE: Rgba<i32> = Rgba([21, 63, 70, 255]);
pub const BLUE_RIBBON: Rgba<i32> = Rgba([79, 102, 255, 255]);
pub const BLUE_ZODIAC: Rgba<i32> = Rgba([17, 31, 65, 255]);
pub const BLUSH_PINK: Rgba<i32> = Rgba([231, 96, 228, 255]);
pub const BOSSANOVA: Rgba<i32> = Rgba([96, 68, 117, 255]);
pub const BOULDER: Rgba<i32> = Rgba([120, 120, 120, 255]);
pub const BREAKER_BAY: Rgba<i32> = Rgba([91, 169, 169, 255]);
pub const BRIGHT_GRAY: Rgba<i32> = Rgba([65, 61, 77, 255]);
pub const BRIGHT_GREEN: Rgba<i32> = Rgba([96, 248, 2, 255]);
pub const BRIGHT_SUN: Rgba<i32> = Rgba([255, 218, 56, 255]);
pub const BRONZETONE: Rgba<i32> = Rgba([74, 62, 12, 255]);
pub const BROOM: Rgba<i32> = Rgba([255, 241, 51, 255]);
pub const BUCCANEER: Rgba<i32> = Rgba([101, 51, 51, 255]);
pub const BUD: Rgba<i32> = Rgba([170, 171, 157, 255]);
pub const BURNT_SIENNA: Rgba<i32> = Rgba([235, 114, 80, 255]);
pub const BUTTERFLY_BUSH: Rgba<i32> = Rgba([96, 72, 133, 255]);
pub const CABBAGE_PONT: Rgba<i32> = Rgba([60, 78, 59, 255]);
pub const CADILLAC: Rgba<i32> = Rgba([196, 96, 114, 255]);
pub const CALIFORNIA: Rgba<i32> = Rgba([255, 156, 12, 255]);
pub const CAMARONE: Rgba<i32> = Rgba([28, 88, 23, 255]);
pub const CAPE_COD: Rgba<i32> = Rgba([59, 67, 71, 255]);
pub const CAPE_PALLISER: Rgba<i32> = Rgba([163, 116, 81, 255]);
pub const CARNATION: Rgba<i32> = Rgba([230, 89, 92, 255]);
pub const CASPER: Rgba<i32> = Rgba([181, 194, 217, 255]);
pub const CASTRO: Rgba<i32> = Rgba([77, 11, 35, 255]);
pub const CEDAR: Rgba<i32> = Rgba([51, 18, 4, 255]);
pub const CERULEAN_BLUE: Rgba<i32> = Rgba([51, 84, 195, 255]);
pub const CHARTREUSE: Rgba<i32> = Rgba([127, 255, 0, 255]);
pub const CHATEAU_GREEN: Rgba<i32> = Rgba([49, 154, 68, 255]);
pub const CHATELLE: Rgba<i32> = Rgba([181, 172, 190, 255]);
pub const CHENIN: Rgba<i32> = Rgba([211, 198, 111, 255]);
pub const CHERRYWOOD: Rgba<i32> = Rgba([94, 25, 17, 255]);
pub const CHETWODE_BLUE: Rgba<i32> = Rgba([141, 137, 223, 255]);
pub const CHOCOLATE: Rgba<i32> = Rgba([51, 0, 0, 255]);
pub const CHRISTI: Rgba<i32> = Rgba([121, 176, 24, 255]);
pub const CINNABAR: Rgba<i32> = Rgba([220, 50, 50, 255]);
pub const CLAIRVOYANT: Rgba<i32> = Rgba([93, 6, 102, 255]);
pub const CLARET: Rgba<i32> = Rgba([128, 26, 52, 255]);
pub const CLASSIC_ROSE: Rgba<i32> = Rgba([251, 209, 240, 255]);
pub const CLAY_CREEK: Rgba<i32> = Rgba([148, 133, 98, 255]);
pub const CLOVER: Rgba<i32> = Rgba([53, 80, 30, 255]);
pub const COCOA_BROWN: Rgba<i32> = Rgba([43, 33, 32, 255]);
pub const COD_GRAY: Rgba<i32> = Rgba([6, 6, 6, 255]);
pub const COMET: Rgba<i32> = Rgba([85, 89, 118, 255]);
pub const CONGO_BROWN: Rgba<i32> = Rgba([87, 59, 55, 255]);
pub const CONIFER: Rgba<i32> = Rgba([149, 232, 87, 255]);
pub const COPPER_CANYON: Rgba<i32> = Rgba([120, 59, 19, 255]);
pub const COPPER_RUST: Rgba<i32> = Rgba([151, 79, 80, 255]);
pub const CORDUROY: Rgba<i32> = Rgba([85, 102, 103, 255]);
pub const CORK: Rgba<i32> = Rgba([63, 39, 26, 255]);
pub const CORNFLOWER: Rgba<i32> = Rgba([144, 195, 232, 255]);
pub const COUNTY_GREEN: Rgba<i32> = Rgba([1, 52, 20, 255]);
pub const CRAIL: Rgba<i32> = Rgba([204, 93, 73, 255]);
pub const CRANBERRY: Rgba<i32> = Rgba([219, 92, 143, 255]);
pub const CRATER_BROWN: Rgba<i32> = Rgba([67, 37, 37, 255]);
pub const CROWN_OF_THORNS: Rgba<i32> = Rgba([128, 44, 45, 255]);
pub const CUMIN: Rgba<i32> = Rgba([150, 67, 22, 255]);
pub const CURIOUS_BLUE: Rgba<i32> = Rgba([22, 173, 254, 255]);
pub const CYAN_AQUA: Rgba<i32> = Rgba([29, 240, 255, 255]);
pub const DAISY_BUSH: Rgba<i32> = Rgba([64, 40, 169, 255]);
pub const DALLAS: Rgba<i32> = Rgba([102, 75, 34, 255]);
pub const DANDELION: Rgba<i32> = Rgba([255, 222, 100, 255]);
pub const DANUBE: Rgba<i32> = Rgba([95, 137, 191, 255]);
pub const DARK_BLUE: Rgba<i32> = Rgba([0, 0, 200, 255]);
pub const DARK_FERN: Rgba<i32> = Rgba([8, 72, 3, 255]);
pub const DEEP_CERULEAN: Rgba<i32> = Rgba([22, 123, 163, 255]);
pub const DINGLEY: Rgba<i32> = Rgba([117, 132, 82, 255]);
pub const DIXIE: Rgba<i32> = Rgba([235, 150, 23, 255]);
pub const DODGER_BLUE: Rgba<i32> = Rgba([43, 143, 255, 255]);
pub const DOLPHIN: Rgba<i32> = Rgba([103, 98, 122, 255]);
pub const DON_JUAN: Rgba<i32> = Rgba([92, 68, 73, 255]);
pub const DORADO: Rgba<i32> = Rgba([104, 86, 84, 255]);
pub const DRIFTWOOD: Rgba<i32> = Rgba([160, 118, 58, 255]);
pub const DULL_LAVENDER: Rgba<i32> = Rgba([146, 136, 205, 255]);
pub const DUNE: Rgba<i32> = Rgba([53, 44, 41, 255]);
pub const EASTERN_BLUE: Rgba<i32> = Rgba([0, 160, 170, 255]);
pub const EAST_BAY: Rgba<i32> = Rgba([74, 71, 129, 255]);
pub const EAST_SIDE: Rgba<i32> = Rgba([174, 145, 214, 255]);
pub const EBONY_CLAY: Rgba<i32> = Rgba([43, 42, 68, 255]);
pub const EDWARD: Rgba<i32> = Rgba([161, 172, 173, 255]);
pub const EGGPLANT: Rgba<i32> = Rgba([78, 50, 69, 255]);
pub const ELECTRIC_VIOLET: Rgba<i32> = Rgba([127, 0, 255, 255]);
pub const EL_SALVA: Rgba<i32> = Rgba([144, 67, 52, 255]);
pub const EMERALD: Rgba<i32> = Rgba([27, 197, 109, 255]);
pub const EQUATOR: Rgba<i32> = Rgba([224, 194, 101, 255]);
pub const FIORD: Rgba<i32> = Rgba([66, 84, 109, 255]);
pub const FLAMENCO: Rgba<i32> = Rgba([255, 120, 0, 255]);
pub const FLAMINGO: Rgba<i32> = Rgba([239, 90, 50, 255]);
pub const FLUSH_MAHOGANY: Rgba<i32> = Rgba([203, 61, 64, 255]);
pub const FLUSH_ORANGE: Rgba<i32> = Rgba([255, 127, 0, 255]);
pub const FRENCH_ROSE: Rgba<i32> = Rgba([240, 91, 147, 255]);
pub const FRIAR_GRAY: Rgba<i32> = Rgba([126, 123, 115, 255]);
pub const FUSCOUS_GRAY: Rgba<i32> = Rgba([77, 74, 72, 255]);
pub const GALLIANO: Rgba<i32> = Rgba([213, 178, 28, 255]);
pub const GEYSER: Rgba<i32> = Rgba([213, 229, 237, 255]);
pub const GLACIER: Rgba<i32> = Rgba([124, 175, 201, 255]);
pub const GOLDENROD: Rgba<i32> = Rgba([233, 207, 94, 255]);
pub const GOLDEN_DREAM: Rgba<i32> = Rgba([233, 203, 24, 255]);
pub const GOLDEN_FIZZ: Rgba<i32> = Rgba([250, 255, 79, 255]);
pub const GOLDEN_SAND: Rgba<i32> = Rgba([255, 227, 132, 255]);
pub const GOLDEN_TAINOI: Rgba<i32> = Rgba([254, 202, 80, 255]);
pub const GOLD_TIPS: Rgba<i32> = Rgba([226, 196, 49, 255]);
pub const GOVERNOR_BAY: Rgba<i32> = Rgba([105, 74, 202, 255]);
pub const GO_BEN: Rgba<i32> = Rgba([119, 108, 81, 255]);
pub const GRANNY_SMITH: Rgba<i32> = Rgba([131, 162, 161, 255]);
pub const GRAPE: Rgba<i32> = Rgba([62, 28, 87, 255]);
pub const GRAVEL: Rgba<i32> = Rgba([68, 68, 76, 255]);
pub const GRAY: Rgba<i32> = Rgba([128, 128, 128, 255]);
pub const GREEN: Rgba<i32> = Rgba([0, 255, 0, 112]);
pub const GREEN_HOUSE: Rgba<i32> = Rgba([52, 84, 12, 255]);
pub const GREEN_LEAF: Rgba<i32> = Rgba([73, 120, 17, 255]);
pub const GUNSMOKE: Rgba<i32> = Rgba([140, 140, 140, 255]);
pub const GUN_POWDER: Rgba<i32> = Rgba([61, 58, 78, 255]);
pub const GURKHA: Rgba<i32> = Rgba([149, 149, 115, 255]);
pub const HACIENDA: Rgba<i32> = Rgba([136, 119, 7, 255]);
pub const HAITI: Rgba<i32> = Rgba([25, 23, 54, 255]);
pub const HALF_BAKED: Rgba<i32> = Rgba([125, 191, 197, 255]);
pub const HAMPTON: Rgba<i32> = Rgba([228, 213, 173, 255]);
pub const HEATH: Rgba<i32> = Rgba([91, 30, 30, 255]);
pub const HEAVY_METAL: Rgba<i32> = Rgba([49, 57, 49, 255]);
pub const HORIZON: Rgba<i32> = Rgba([75, 139, 166, 255]);
pub const HOT_PINK: Rgba<i32> = Rgba([249, 101, 189, 255]);
pub const HUSK: Rgba<i32> = Rgba([190, 171, 94, 255]);
pub const INDIAN_KHAKI: Rgba<i32> = Rgba([203, 185, 151, 255]);
pub const IROKO: Rgba<i32> = Rgba([73, 51, 36, 255]);
pub const IRONSTONE: Rgba<i32> = Rgba([146, 81, 68, 255]);
pub const JACARTA: Rgba<i32> = Rgba([50, 46, 104, 255]);
pub const JAFFA: Rgba<i32> = Rgba([255, 145, 79, 255]);
pub const JAMBALAYA: Rgba<i32> = Rgba([99, 50, 30, 255]);
pub const JAZZBERRY_JAM: Rgba<i32> = Rgba([160, 2, 75, 255]);
pub const JET_STREAM: Rgba<i32> = Rgba([181, 211, 210, 255]);
pub const JEWEL: Rgba<i32> = Rgba([23, 119, 79, 255]);
pub const JON: Rgba<i32> = Rgba([62, 38, 41, 255]);
pub const JUNGLE_GREEN: Rgba<i32> = Rgba([17, 172, 143, 255]);
pub const KABUL: Rgba<i32> = Rgba([96, 77, 64, 255]);
pub const KASHMIR_BLUE: Rgba<i32> = Rgba([78, 105, 135, 255]);
pub const KELP: Rgba<i32> = Rgba([70, 68, 51, 255]);
pub const KIMBERLY: Rgba<i32> = Rgba([100, 82, 126, 255]);
pub const KOURNIKOVA: Rgba<i32> = Rgba([251, 235, 127, 255]);
pub const LAVENDER_MAGENTA: Rgba<i32> = Rgba([255, 117, 224, 255]);
pub const LAVENDER_PURPLE: Rgba<i32> = Rgba([141, 120, 168, 255]);
pub const LAVENDER_ROSE: Rgba<i32> = Rgba([225, 128, 206, 255]);
pub const LEATHER: Rgba<i32> = Rgba([151, 107, 75, 255]);
pub const LIMA: Rgba<i32> = Rgba([96, 197, 27, 255]);
pub const LISBON_BROWN: Rgba<i32> = Rgba([69, 67, 41, 255]);
pub const LIVID_BROWN: Rgba<i32> = Rgba([89, 48, 59, 255]);
pub const LOG_CABIN: Rgba<i32> = Rgba([31, 39, 26, 255]);
pub const LONESTAR: Rgba<i32> = Rgba([111, 6, 6, 255]);
pub const LUXOR_GOLD: Rgba<i32> = Rgba([153, 131, 44, 255]);
pub const MABEL: Rgba<i32> = Rgba([211, 236, 241, 255]);
pub const MACARONI_AND_CHEESE: Rgba<i32> = Rgba([255, 178, 125, 255]);
pub const MADISON: Rgba<i32> = Rgba([20, 46, 104, 255]);
pub const MADRAS: Rgba<i32> = Rgba([65, 52, 15, 255]);
pub const MAGENTA_FUCHSIA: Rgba<i32> = Rgba([255, 0, 255, 255]);
pub const MALACHITE: Rgba<i32> = Rgba([28, 216, 94, 255]);
pub const MALIBU: Rgba<i32> = Rgba([155, 209, 255, 255]);
pub const MAMBA: Rgba<i32> = Rgba([136, 120, 131, 255]);
pub const MANDALAY: Rgba<i32> = Rgba([168, 121, 39, 255]);
pub const MARINER: Rgba<i32> = Rgba([30, 118, 226, 255]);
pub const MAROON_FLUSH: Rgba<i32> = Rgba([174, 24, 69, 255]);
pub const MARTINIQUE: Rgba<i32> = Rgba([49, 47, 83, 255]);
pub const MASALA: Rgba<i32> = Rgba([63, 63, 63, 255]);
pub const MATISSE: Rgba<i32> = Rgba([51, 102, 153, 255]);
pub const MATTERHORN: Rgba<i32> = Rgba([76, 52, 60, 255]);
pub const MAUVELOUS: Rgba<i32> = Rgba([255, 150, 181, 255]);
pub const MEDIUM_CARMINE: Rgba<i32> = Rgba([181, 62, 59, 255]);
pub const MEDIUM_PURPLE: Rgba<i32> = Rgba([179, 132, 255, 255]);
pub const MELANIE: Rgba<i32> = Rgba([218, 182, 204, 255]);
pub const MERLOT: Rgba<i32> = Rgba([134, 22, 34, 255]);
pub const METALLIC_BRONZE: Rgba<i32> = Rgba([77, 64, 34, 255]);
pub const METEORITE: Rgba<i32> = Rgba([74, 23, 119, 255]);
pub const MILLBROOK: Rgba<i32> = Rgba([88, 61, 46, 255]);
pub const MINE_SHAFT: Rgba<i32> = Rgba([52, 52, 52, 255]);
pub const MINT_GREEN: Rgba<i32> = Rgba([85, 255, 160, 255]);
pub const MIRAGE: Rgba<i32> = Rgba([27, 31, 42, 255]);
pub const MONDO: Rgba<i32> = Rgba([73, 66, 50, 255]);
pub const MONGOOSE: Rgba<i32> = Rgba([181, 164, 125, 255]);
pub const MOROCCO_BROWN: Rgba<i32> = Rgba([75, 32, 11, 255]);
pub const MORTAR: Rgba<i32> = Rgba([82, 63, 80, 255]);
pub const MOUNTAIN_MEADOW: Rgba<i32> = Rgba([48, 186, 135, 255]);
pub const MOUNTAIN_MIST: Rgba<i32> = Rgba([144, 144, 144, 255]);
pub const MULE_FAWN: Rgba<i32> = Rgba([149, 80, 51, 255]);
pub const MYSTIC: Rgba<i32> = Rgba([223, 232, 233, 255]);
pub const NIGHT_SHADZ: Rgba<i32> = Rgba([154, 49, 77, 255]);
pub const NORWAY: Rgba<i32> = Rgba([166, 187, 153, 255]);
pub const OLD_GOLD: Rgba<i32> = Rgba([214, 184, 46, 255]);
pub const OLD_LAVENDER: Rgba<i32> = Rgba([119, 101, 125, 255]);
pub const ONAHAU: Rgba<i32> = Rgba([200, 246, 254, 255]);
pub const OREGON: Rgba<i32> = Rgba([141, 56, 0, 255]);
pub const OSLO_GRAY: Rgba<i32> = Rgba([140, 150, 150, 255]);
pub const OUTER_SPACE: Rgba<i32> = Rgba([46, 56, 59, 255]);
pub const PABLO: Rgba<i32> = Rgba([121, 119, 101, 255]);
pub const PACIFIC_BLUE: Rgba<i32> = Rgba([33, 171, 207, 255]);
pub const PACIFIKA: Rgba<i32> = Rgba([126, 134, 49, 255]);
pub const PEAT: Rgba<i32> = Rgba([119, 105, 79, 255]);
pub const PERIWINKLE_GRAY: Rgba<i32> = Rgba([190, 204, 223, 255]);
pub const PERSIAN_BLUE: Rgba<i32> = Rgba([9, 61, 191, 255]);
pub const PERSIAN_PINK: Rgba<i32> = Rgba([245, 133, 191, 255]);
pub const PERSIAN_PLUM: Rgba<i32> = Rgba([111, 32, 36, 255]);
pub const PERU_TAN: Rgba<i32> = Rgba([135, 58, 0, 255]);
pub const PESTO: Rgba<i32> = Rgba([137, 120, 67, 255]);
pub const PETITE_ORCHID: Rgba<i32> = Rgba([216, 152, 144, 255]);
pub const PICTON_BLUE: Rgba<i32> = Rgba([91, 186, 240, 255]);
pub const PIGMENT_INDIGO: Rgba<i32> = Rgba([87, 21, 144, 255]);
pub const PINE_GREEN: Rgba<i32> = Rgba([0, 117, 101, 255]);
pub const PINK_FLAMINGO: Rgba<i32> = Rgba([221, 79, 255, 255]);
pub const PLUM: Rgba<i32> = Rgba([125, 36, 122, 255]);
pub const POLO_BLUE: Rgba<i32> = Rgba([146, 155, 187, 255]);
pub const PORTAGE: Rgba<i32> = Rgba([141, 175, 255, 255]);
pub const PORT_GORE: Rgba<i32> = Rgba([43, 40, 84, 255]);
pub const POTTERS_CLAY: Rgba<i32> = Rgba([140, 84, 60, 255]);
pub const PUERTO_RICO: Rgba<i32> = Rgba([0, 206, 180, 255]);
pub const PUNCH: Rgba<i32> = Rgba([219, 71, 38, 255]);
pub const PURPLE: Rgba<i32> = Rgba([111, 39, 168, 255]);
pub const PURPLE_HEART: Rgba<i32> = Rgba([160, 87, 234, 255]);
pub const QUINCY: Rgba<i32> = Rgba([96, 68, 48, 255]);
pub const RANGITOTO: Rgba<i32> = Rgba([49, 48, 36, 255]);
pub const RAW_SIENNA: Rgba<i32> = Rgba([198, 124, 78, 255]);
pub const RED: Rgba<i32> = Rgba([255, 0, 0, 112]);
pub const RED_BEECH: Rgba<i32> = Rgba([130, 62, 16, 255]);
pub const REGENT_ST_BLUE: Rgba<i32> = Rgba([159, 209, 229, 255]);
pub const RENO_SAND: Rgba<i32> = Rgba([163, 96, 0, 255]);
pub const RIPTIDE: Rgba<i32> = Rgba([131, 252, 245, 255]);
pub const ROCK_BLUE: Rgba<i32> = Rgba([152, 171, 198, 255]);
pub const ROMAN: Rgba<i32> = Rgba([208, 80, 80, 255]);
pub const ROMAN_COFFEE: Rgba<i32> = Rgba([127, 92, 69, 255]);
pub const ROSE: Rgba<i32> = Rgba([255, 0, 127, 255]);
pub const ROYAL_HEATH: Rgba<i32> = Rgba([170, 48, 114, 255]);
pub const ROYAL_PURPLE: Rgba<i32> = Rgba([107, 49, 154, 255]);
pub const RUM: Rgba<i32> = Rgba([109, 90, 128, 255]);
pub const RUSSET: Rgba<i32> = Rgba([138, 73, 38, 255]);
pub const RUSTY_NAIL: Rgba<i32> = Rgba([131, 79, 13, 255]);
pub const SADDLE: Rgba<i32> = Rgba([84, 57, 42, 255]);
pub const SAHARA: Rgba<i32> = Rgba([185, 164, 23, 255]);
pub const SAIL: Rgba<i32> = Rgba([184, 219, 240, 255]);
pub const SALT_BOX: Rgba<i32> = Rgba([107, 92, 108, 255]);
pub const SANDSTONE: Rgba<i32> = Rgba([121, 110, 97, 255]);
pub const SANGUINE_BROWN: Rgba<i32> = Rgba([134, 59, 49, 255]);
pub const SAN_JUAN: Rgba<i32> = Rgba([62, 82, 114, 255]);
pub const SAN_MARINO: Rgba<i32> = Rgba([55, 97, 155, 255]);
pub const SCAMPI: Rgba<i32> = Rgba([98, 95, 167, 255]);
pub const SCARLET: Rgba<i32> = Rgba([253, 32, 3, 255]);
pub const SCARPA_FLOW: Rgba<i32> = Rgba([81, 84, 101, 255]);
pub const SCHOOL_BUS_YELLOW: Rgba<i32> = Rgba([253, 221, 3, 255]);
pub const SCOOTER: Rgba<i32> = Rgba([48, 208, 234, 255]);
pub const SCORPION: Rgba<i32> = Rgba([113, 99, 99, 255]);
pub const SCREAMIN_GREEN: Rgba<i32> = Rgba([79, 255, 89, 255]);
pub const SEAGULL: Rgba<i32> = Rgba([133, 213, 247, 255]);
pub const SEANCE: Rgba<i32> = Rgba([140, 58, 166, 255]);
pub const SEA_GREEN: Rgba<i32> = Rgba([56, 150, 97, 255]);
pub const SEA_PINK: Rgba<i32> = Rgba([221, 136, 144, 255]);
pub const SEPIA: Rgba<i32> = Rgba([119, 68, 23, 255]);
pub const SEPIA_SKIN: Rgba<i32> = Rgba([154, 83, 49, 255]);
pub const SHARK: Rgba<i32> = Rgba([36, 36, 36, 255]);
pub const SHIP_COVE: Rgba<i32> = Rgba([110, 140, 182, 255]);
pub const SHUTTLE_GRAY: Rgba<i32> = Rgba([106, 107, 118, 255]);
pub const SILVER: Rgba<i32> = Rgba([192, 192, 192, 255]);
pub const SILVER_CHALICE: Rgba<i32> = Rgba([175, 175, 175, 255]);
pub const SILVER_SAND: Rgba<i32> = Rgba([200, 200, 200, 150]);
pub const SIROCCO: Rgba<i32> = Rgba([107, 132, 139, 255]);
pub const SMALT: Rgba<i32> = Rgba([49, 49, 154, 255]);
pub const SOLID_PINK: Rgba<i32> = Rgba([125, 55, 65, 255]);
pub const SORRELL_BROWN: Rgba<i32> = Rgba([182, 175, 130, 255]);
pub const SPRAY: Rgba<i32> = Rgba([122, 217, 232, 255]);
pub const SPRING_GREEN: Rgba<i32> = Rgba([48, 255, 110, 255]);
pub const SPUN_PEARL: Rgba<i32> = Rgba([174, 168, 186, 255]);
pub const SQUIRREL: Rgba<i32> = Rgba([140, 130, 116, 255]);
pub const STACK: Rgba<i32> = Rgba([144, 148, 144, 255]);
pub const STAR_DUST: Rgba<i32> = Rgba([160, 160, 160, 255]);
pub const STILETTO: Rgba<i32> = Rgba([149, 48, 48, 255]);
pub const STORM_DUST: Rgba<i32> = Rgba([96, 96, 96, 255]);
pub const STORM_GRAY: Rgba<i32> = Rgba([114, 114, 131, 255]);
pub const STRAW: Rgba<i32> = Rgba([191, 176, 124, 255]);
pub const ST_TROPAZ: Rgba<i32> = Rgba([11, 80, 143, 255]);
pub const SUBMARINE: Rgba<i32> = Rgba([185, 194, 195, 255]);
pub const SULU: Rgba<i32> = Rgba([191, 233, 115, 255]);
pub const SUNGLO: Rgba<i32> = Rgba([253, 114, 114, 255]);
pub const SUNSET_ORANGE: Rgba<i32> = Rgba([255, 79, 79, 255]);
pub const SWISS_COFFEE: Rgba<i32> = Rgba([213, 203, 204, 255]);
pub const SYCAMORE: Rgba<i32> = Rgba([154, 148, 49, 255]);
pub const TACAO: Rgba<i32> = Rgba([233, 183, 128, 255]);
pub const TACHA: Rgba<i32> = Rgba([212, 192, 100, 255]);
pub const TAMARIND: Rgba<i32> = Rgba([50, 15, 8, 255]);
pub const TAN: Rgba<i32> = Rgba([217, 174, 137, 255]);
pub const TAN_HIDE: Rgba<i32> = Rgba([248, 158, 92, 255]);
pub const TAUPE: Rgba<i32> = Rgba([73, 59, 50, 255]);
pub const THATCH_GREEN: Rgba<i32> = Rgba([65, 65, 35, 255]);
pub const THUNDER: Rgba<i32> = Rgba([52, 43, 45, 255]);
pub const THUNDERBIRD: Rgba<i32> = Rgba([192, 30, 30, 255]);
pub const TIARA: Rgba<i32> = Rgba([197, 216, 219, 255]);
pub const TOSCA: Rgba<i32> = Rgba([142, 66, 66, 255]);
pub const TREEHOUSE: Rgba<i32> = Rgba([51, 35, 27, 255]);
pub const TREE_POPPY: Rgba<i32> = Rgba([255, 162, 31, 255]);
pub const TROUT: Rgba<i32> = Rgba([78, 87, 99, 255]);
pub const TRUE_V: Rgba<i32> = Rgba([122, 116, 218, 255]);
pub const TUATARA: Rgba<i32> = Rgba([59, 59, 59, 255]);
pub const TUMBLEWEED: Rgba<i32> = Rgba([235, 166, 135, 255]);
pub const TUNA: Rgba<i32> = Rgba([55, 55, 73, 255]);
pub const TUNDORA: Rgba<i32> = Rgba([73, 70, 70, 255]);
pub const TURKISH_ROSE: Rgba<i32> = Rgba([175, 105, 128, 255]);
pub const TURMERIC: Rgba<i32> = Rgba([204, 181, 72, 255]);
pub const TUSSOCK: Rgba<i32> = Rgba([205, 153, 73, 255]);
pub const TWINE: Rgba<i32> = Rgba([190, 150, 92, 255]);
pub const ULTRAMARINE: Rgba<i32> = Rgba([39, 34, 180, 255]);
pub const VALENCIA: Rgba<i32> = Rgba([238, 85, 70, 255]);
pub const VENICE_BLUE: Rgba<i32> = Rgba([13, 88, 130, 255]);
pub const VERMILION: Rgba<i32> = Rgba([253, 62, 3, 255]);
pub const VESUVIUS: Rgba<i32> = Rgba([183, 75, 15, 255]);
pub const VIDA_LOCA: Rgba<i32> = Rgba([79, 128, 17, 255]);
pub const VIKING: Rgba<i32> = Rgba([97, 200, 225, 255]);
pub const VIOLA: Rgba<i32> = Rgba([205, 152, 186, 255]);
pub const VIOLET: Rgba<i32> = Rgba([38, 9, 66, 255]);
pub const VIOLET_EGGPLANT: Rgba<i32> = Rgba([174, 16, 176, 255]);
pub const VIRIDIAN: Rgba<i32> = Rgba([49, 134, 114, 255]);
pub const VIVID_TANGERINE: Rgba<i32> = Rgba([239, 141, 126, 255]);
pub const VIVID_VIOLET: Rgba<i32> = Rgba([121, 49, 134, 255]);
pub const VOODOO: Rgba<i32> = Rgba([107, 68, 99, 255]);
pub const WALNUT: Rgba<i32> = Rgba([117, 61, 25, 255]);
pub const WATERLOO: Rgba<i32> = Rgba([117, 125, 151, 255]);
pub const WATTLE: Rgba<i32> = Rgba([229, 212, 73, 255]);
pub const WELL_READ: Rgba<i32> = Rgba([192, 59, 59, 255]);
pub const WHITE: Rgba<i32> = Rgba([255, 255, 255, 255]);
pub const WILD_BLUE_YONDER: Rgba<i32> = Rgba([128, 133, 184, 255]);
pub const WILD_STRAWBERRY: Rgba<i32> = Rgba([255, 66, 152, 255]);
pub const WOODSMOKE: Rgba<i32> = Rgba([15, 15, 15, 255]);
pub const YELLOW: Rgba<i32> = Rgba([255, 255, 0, 112]);
pub const YELLOW_SEA: Rgba<i32> = Rgba([255, 172, 0, 240]);
pub const ZEST: Rgba<i32> = Rgba([227, 125, 22, 255]);
pub const ZEUS: Rgba<i32> = Rgba([39, 33, 26, 255]);
pub const ZIGGURAT: Rgba<i32> = Rgba([190, 223, 232, 255]);
pub const ZOMBIE: Rgba<i32> = Rgba([228, 219, 162, 255]);
pub const ZUCCINI: Rgba<i32> = Rgba([30, 80, 48, 255]);

lazy_static! {
  pub static ref BLOCKTYPE_COLOR_MAP: HashMap<BlockType, Rgba<i32>> = hashmap! {
    BlockType::Dirt => LEATHER,
    BlockType::Stone => GRAY,
    BlockType::Grass => MALACHITE,
    BlockType::Plants => EMERALD,
    BlockType::Torches => SCHOOL_BUS_YELLOW,
    BlockType::Trees => LEATHER,
    BlockType::Iron => BEAVER,
    BlockType::Copper => CUMIN,
    BlockType::Gold => SAHARA,
    BlockType::Silver => SUBMARINE,
    BlockType::ClosedDoor => PEAT,
    BlockType::OpenDoor => PEAT,
    BlockType::Heart => MAROON_FLUSH,
    BlockType::Bottles => SEAGULL,
    BlockType::Tables => ANTIQUE_BRASS,
    BlockType::Chairs => ANTIQUE_BRASS,
    BlockType::Anvils => SQUIRREL,
    BlockType::Furnaces => STACK,
    BlockType::WorkBenches => ANTIQUE_BRASS,
    BlockType::Platforms => ANTIQUE_BRASS,
    BlockType::Saplings => CAPE_PALLISER,
    BlockType::Containers => GOLDENROD,
    BlockType::Demonite => SCAMPI,
    BlockType::CorruptGrass => CHETWODE_BLUE,
    BlockType::CorruptPlants => TRUE_V,
    BlockType::Ebonstone => RUM,
    BlockType::DemonAltar => OLD_LAVENDER,
    BlockType::Sunflower => GOLD_TIPS,
    BlockType::Pots => COPPER_RUST,
    BlockType::PiggyBank => TURKISH_ROSE,
    BlockType::WoodBlock => CAPE_PALLISER,
    BlockType::ShadowOrbs => LAVENDER_PURPLE,
    BlockType::CorruptThorns => BLUE_BELL,
    BlockType::Candles => SCHOOL_BUS_YELLOW,
    BlockType::Chandeliers => TUMBLEWEED,
    BlockType::Jackolanterns => TIARA,
    BlockType::Presents => CARNATION,
    BlockType::Meteorite => DORADO,
    BlockType::GrayBrick => MOUNTAIN_MIST,
    BlockType::RedBrick => MEDIUM_CARMINE,
    BlockType::ClayBlock => IRONSTONE,
    BlockType::BlueDungeonBrick => FIORD,
    BlockType::HangingLanterns => KOURNIKOVA,
    BlockType::GreenDungeonBrick => AXOLOTL,
    BlockType::PinkDungeonBrick => VOODOO,
    BlockType::GoldBrick => SAHARA,
    BlockType::SilverBrick => SUBMARINE,
    BlockType::CopperBrick => CUMIN,
    BlockType::Spikes => GRAY,
    BlockType::WaterCandle => DODGER_BLUE,
    BlockType::Books => ROYAL_HEATH,
    BlockType::Cobweb => SUBMARINE,
    BlockType::Vines => APPLE,
    BlockType::Sand => BRIGHT_SUN,
    BlockType::Glass => ONAHAU,
    BlockType::SignVec => ANTIQUE_BRASS,
    BlockType::Obsidian => PORT_GORE,
    BlockType::Ash => GRAVEL,
    BlockType::Hellstone => TOSCA,
    BlockType::Mud => DON_JUAN,
    BlockType::JungleGrass => ATLANTIS,
    BlockType::JunglePlants => ATLANTIS,
    BlockType::JungleVines => CHRISTI,
    BlockType::Sapphire => SHIP_COVE,
    BlockType::Ruby => CADILLAC,
    BlockType::Emerald => SEA_GREEN,
    BlockType::Topaz => DRIFTWOOD,
    BlockType::Amethyst => SEANCE,
    BlockType::Diamond => HALF_BAKED,
    BlockType::JungleThorns => TWINE,
    BlockType::MushroomGrass => AZURE_RADIANCE,
    BlockType::MushroomPlants => SORRELL_BROWN,
    BlockType::MushroomTrees => SORRELL_BROWN,
    BlockType::Plants2 => EMERALD,
    BlockType::JunglePlants2 => LIMA,
    BlockType::ObsidianBrick => SHARK,
    BlockType::HellstoneBrick => TOSCA,
    BlockType::Hellforge => VALENCIA,
    BlockType::ClayPot => SANDSTONE,
    BlockType::Beds => ANTIQUE_BRASS,
    BlockType::Cactus => GREEN_LEAF,
    BlockType::Coral => PERSIAN_PINK,
    BlockType::ImmatureHerbs => FLAMENCO,
    BlockType::MatureHerbs => FLAMENCO,
    BlockType::BloomingHerbs => FLAMENCO,
    BlockType::Tombstones => SILVER,
    BlockType::Loom => ANTIQUE_BRASS,
    BlockType::Pianos => ANTIQUE_BRASS,
    BlockType::Dressers => ANTIQUE_BRASS,
    BlockType::Benches => ANTIQUE_BRASS,
    BlockType::Bathtubs => STACK,
    BlockType::Banners => VENICE_BLUE,
    BlockType::Lampposts => GEYSER,
    BlockType::Lamps => SCHOOL_BUS_YELLOW,
    BlockType::Kegs => ANTIQUE_BRASS,
    BlockType::ChineseLanterns => TREE_POPPY,
    BlockType::CookingPots => STACK,
    BlockType::Safes => STACK,
    BlockType::SkullLanterns => SCHOOL_BUS_YELLOW,
    BlockType::TrashCan => STACK,
    BlockType::Candelabras => SCHOOL_BUS_YELLOW,
    BlockType::Bookcases => ANTIQUE_BRASS,
    BlockType::Thrones => WATTLE,
    BlockType::Bowls => LEATHER,
    BlockType::GrandfatherClocks => ANTIQUE_BRASS,
    BlockType::Statues => STACK,
    BlockType::Sawmill => ANTIQUE_BRASS,
    BlockType::Cobalt => ST_TROPAZ,
    BlockType::Mythril => BREAKER_BAY,
    BlockType::HallowedGrass => SEAGULL,
    BlockType::HallowedPlants => MOUNTAIN_MEADOW,
    BlockType::Adamantite => CLARET,
    BlockType::Ebonsand => DOLPHIN,
    BlockType::HallowedPlants2 => SCOOTER,
    BlockType::TinkerersWorkbench => ANTIQUE_BRASS,
    BlockType::HallowedVines => PACIFIC_BLUE,
    BlockType::Pearlsand => BIZARRE,
    BlockType::Pearlstone => CHATELLE,
    BlockType::PearlstoneBrick => BIZARRE,
    BlockType::IridescentBrick => SALT_BOX,
    BlockType::Mudstone => DON_JUAN,
    BlockType::CobaltBrick => ST_TROPAZ,
    BlockType::MythrilBrick => BREAKER_BAY,
    BlockType::Silt => SHUTTLE_GRAY,
    BlockType::WoodenBeam => IROKO,
    BlockType::CrystalBall => PORTAGE,
    BlockType::DiscoBall => REGENT_ST_BLUE,
    BlockType::MagicalIceBlock => SEAGULL,
    BlockType::Mannequin => ANTIQUE_BRASS,
    BlockType::Crystals => LAVENDER_MAGENTA,
    BlockType::ActiveStoneBlock => STAR_DUST,
    BlockType::InactiveStoneBlock => MINE_SHAFT,
    BlockType::Lever => STACK,
    BlockType::AdamantiteForge => ALIZARIN_CRIMSON,
    BlockType::MythrilAnvil => NORWAY,
    BlockType::PressurePlates => SUNGLO,
    BlockType::Switches => SWISS_COFFEE,
    BlockType::Traps => STACK,
    BlockType::Boulder => STORM_DUST,
    BlockType::MusicBoxes => ANTIQUE_BRASS,
    BlockType::DemoniteBrick => SCAMPI,
    BlockType::Explosives => WELL_READ,
    BlockType::InletPump => STACK,
    BlockType::OutletPump => STACK,
    BlockType::Timers => STACK,
    BlockType::CandyCaneBlock => THUNDERBIRD,
    BlockType::GreenCandyCaneBlock => MALACHITE,
    BlockType::SnowBlock => MABEL,
    BlockType::SnowBrick => JET_STREAM,
    BlockType::HolidayLights => CINNABAR,
    BlockType::AdamantiteBeam => CLARET,
    BlockType::SandstoneBrick => HUSK,
    BlockType::EbonstoneBrick => WILD_BLUE_YONDER,
    BlockType::RedStucco => VIVID_TANGERINE,
    BlockType::YellowStucco => HUSK,
    BlockType::GreenStucco => GRANNY_SMITH,
    BlockType::GrayStucco => BUD,
    BlockType::Ebonwood => DOLPHIN,
    BlockType::RichMahogany => AU_CHICO,
    BlockType::Pearlwood => CLAY_CREEK,
    BlockType::RainbowBrick => DARK_BLUE,
    BlockType::IceBlock => CORNFLOWER,
    BlockType::BreakableIce => SAIL,
    BlockType::CorruptIce => EAST_SIDE,
    BlockType::HallowedIce => MELANIE,
    BlockType::Stalactite => STORM_DUST,
    BlockType::Tin => CLAY_CREEK,
    BlockType::Lead => SAN_JUAN,
    BlockType::Tungsten => AMULET,
    BlockType::Platinum => ROCK_BLUE,
    BlockType::PineTree => ZOMBIE,
    BlockType::ChristmasTree => SEA_GREEN,
    BlockType::Sinks => CASPER,
    BlockType::PlatinumCandelabra => SCHOOL_BUS_YELLOW,
    BlockType::PlatinumCandle => SCHOOL_BUS_YELLOW,
    BlockType::TinBrick => CLAY_CREEK,
    BlockType::TungstenBrick => AMULET,
    BlockType::PlatinumBrick => ROCK_BLUE,
    BlockType::ExposedGems => MAGENTA_FUCHSIA,
    BlockType::GreenMoss => VIRIDIAN,
    BlockType::BrownMoss => PACIFIKA,
    BlockType::RedMoss => SANGUINE_BROWN,
    BlockType::BlueMoss => VENICE_BLUE,
    BlockType::PurpleMoss => VIVID_VIOLET,
    BlockType::LongMoss => STORM_DUST,
    BlockType::SmallPiles => GURKHA,
    BlockType::LargePiles => MAGENTA_FUCHSIA,
    BlockType::LargePiles2 => MAGENTA_FUCHSIA,
    BlockType::CactusBlock => GREEN_LEAF,
    BlockType::Cloud => BABY_BLUE,
    BlockType::MushroomBlock => SORRELL_BROWN,
    BlockType::LivingWood => LEATHER,
    BlockType::LeafBlock => MALACHITE,
    BlockType::SlimeBlock => AZURE_RADIANCE,
    BlockType::BoneBlock => AVOCADO,
    BlockType::FleshBlock => MERLOT,
    BlockType::RainCloud => AMETHYST_SMOKE,
    BlockType::FrozenSlimeBlock => VIKING,
    BlockType::Asphalt => ARMADILLO,
    BlockType::FleshGrass => ROMAN,
    BlockType::FleshIce => PETITE_ORCHID,
    BlockType::FleshWeeds => FLUSH_MAHOGANY,
    BlockType::Sunplate => GALLIANO,
    BlockType::Crimstone => CROWN_OF_THORNS,
    BlockType::Crimtane => SOLID_PINK,
    BlockType::CrimsonVines => WELL_READ,
    BlockType::IceBrick => GLACIER,
    BlockType::WaterFountain => STACK,
    BlockType::Shadewood => SHUTTLE_GRAY,
    BlockType::Cannon => STACK,
    BlockType::LandMine => WELL_READ,
    BlockType::Chlorophyte => SULU,
    BlockType::SnowballLauncher => STACK,
    BlockType::Rope => PESTO,
    BlockType::Chain => STORM_DUST,
    BlockType::Campfire => FLAMENCO,
    BlockType::Firework => ANTIQUE_BRASS,
    BlockType::Blendomatic => STACK,
    BlockType::MeatGrinder => STACK,
    BlockType::Extractinator => STACK,
    BlockType::Solidifier => STACK,
    BlockType::Palladium => FLAMINGO,
    BlockType::Orichalcum => BLUSH_PINK,
    BlockType::Titanium => FIORD,
    BlockType::Slush => SIROCCO,
    BlockType::Hive => ZEST,
    BlockType::LihzahrdBrick => OREGON,
    BlockType::DyePlants => WHITE,
    BlockType::DyeVat => STACK,
    BlockType::HoneyBlock => CALIFORNIA,
    BlockType::CrispyHoneyBlock => RUSTY_NAIL,
    BlockType::Larva => EQUATOR,
    BlockType::WoodenSpikes => AU_CHICO,
    BlockType::PlantDetritus => MAGENTA_FUCHSIA,
    BlockType::Crimsand => DUNE,
    BlockType::Teleporter => OLD_GOLD,
    BlockType::LifeFruit => CONIFER,
    BlockType::LihzahrdAltar => BROOM,
    BlockType::PlanteraBulb => LAVENDER_ROSE,
    BlockType::MetalBars => EQUATOR,
    BlockType::Painting3x3 => JAMBALAYA,
    BlockType::Painting4x3 => FUSCOUS_GRAY,
    BlockType::Painting6x4 => JAMBALAYA,
    BlockType::ImbuingStation => PORTAGE,
    BlockType::BubbleMachine => ONAHAU,
    BlockType::Painting2x3 => JAMBALAYA,
    BlockType::Painting3x2 => JAMBALAYA,
    BlockType::Autohammer => OSLO_GRAY,
    BlockType::PalladiumColumn => PUNCH,
    BlockType::BubblegumBlock => MAGENTA_FUCHSIA,
    BlockType::Titanstone => ABBEY,
    BlockType::PumpkinBlock => DIXIE,
    BlockType::HayBlock => LUXOR_GOLD,
    BlockType::SpookyWood => PORT_GORE,
    BlockType::Pumpkins => TAN_HIDE,
    BlockType::AmethystGemsparkOff => ROYAL_PURPLE,
    BlockType::TopazGemsparkOff => SYCAMORE,
    BlockType::SapphireGemsparkOff => SMALT,
    BlockType::EmeraldGemsparkOff => CHATEAU_GREEN,
    BlockType::RubyGemsparkOff => NIGHT_SHADZ,
    BlockType::DiamondGemsparkOff => COMET,
    BlockType::AmberGemsparkOff => SEPIA_SKIN,
    BlockType::AmethystGemspark => PINK_FLAMINGO,
    BlockType::TopazGemspark => GOLDEN_FIZZ,
    BlockType::SapphireGemspark => BLUE_RIBBON,
    BlockType::EmeraldGemspark => SCREAMIN_GREEN,
    BlockType::RubyGemspark => SUNSET_ORANGE,
    BlockType::DiamondGemspark => ATHENS_GRAY,
    BlockType::AmberGemspark => JAFFA,
    BlockType::Womannequin => ANTIQUE_BRASS,
    BlockType::FireflyinaBottle => SPRAY,
    BlockType::LightningBuginaBottle => SPRAY,
    BlockType::Cog => PABLO,
    BlockType::StoneSlab => GRAY,
    BlockType::SandStoneSlab => HUSK,
    BlockType::BunnyCage => SPRAY,
    BlockType::SquirrelCage => SPRAY,
    BlockType::MallardDuckCage => SPRAY,
    BlockType::DuckCage => SPRAY,
    BlockType::BirdCage => SPRAY,
    BlockType::BlueJay => SPRAY,
    BlockType::CardinalCage => SPRAY,
    BlockType::FishBowl => SPRAY,
    BlockType::HeavyWorkBench => GRAY,
    BlockType::CopperPlating => CUMIN,
    BlockType::SnailCage => SPRAY,
    BlockType::GlowingSnailCage => SPRAY,
    BlockType::AmmoBox => VIDA_LOCA,
    BlockType::MonarchButterflyJar => SPRAY,
    BlockType::PurpleEmperorButterflyJar => SPRAY,
    BlockType::RedAdmiralButterflyJar => SPRAY,
    BlockType::UlyssesButterflyJar => SPRAY,
    BlockType::SulphurButterflyJar => SPRAY,
    BlockType::TreeNymphButterflyJar => SPRAY,
    BlockType::ZebraSwallowtailButterflyJar => SPRAY,
    BlockType::JuliaButterflyJar => SPRAY,
    BlockType::ScorpionCage => SPRAY,
    BlockType::BlackScorpionCage => SPRAY,
    BlockType::FrogCage => SPRAY,
    BlockType::MouseCage => SPRAY,
    BlockType::BoneWelder => STACK,
    BlockType::FleshCloningVat => STACK,
    BlockType::GlassKiln => STACK,
    BlockType::LihzahrdFurnace => STACK,
    BlockType::LivingLoom => STACK,
    BlockType::SkyMill => STACK,
    BlockType::IceMachine => STACK,
    BlockType::SteampunkBoiler => STACK,
    BlockType::HoneyDispenser => STACK,
    BlockType::PenguinCage => SPRAY,
    BlockType::WormCage => SPRAY,
    BlockType::DynastyWood => WALNUT,
    BlockType::RedDynastyShingles => CRAIL,
    BlockType::BlueDynastyShingles => BREAKER_BAY,
    BlockType::MinecartTrack => MONGOOSE,
    BlockType::Coralstone => BURNT_SIENNA,
    BlockType::BlueJellyfishBowl => SPRAY,
    BlockType::GreenJellyfishBowl => SPRAY,
    BlockType::PinkJellyfishBowl => SPRAY,
    BlockType::ShipInAbottle => QUINCY,
    BlockType::SeaweedPlanter => INDIAN_KHAKI,
    BlockType::BorealWood => KABUL,
    BlockType::PalmWood => HUSK,
    BlockType::PalmTree => DRIFTWOOD,
    BlockType::BeachPiles => HAMPTON,
    BlockType::TinPlating => CLAY_CREEK,
    BlockType::Waterfall => PERSIAN_BLUE,
    BlockType::Lavafall => SCARLET,
    BlockType::Confetti => ONAHAU,
    BlockType::ConfettiBlack => WOODSMOKE,
    BlockType::CopperCoinPile => BURNT_SIENNA,
    BlockType::SilverCoinPile => EDWARD,
    BlockType::GoldCoinPile => TURMERIC,
    BlockType::PlatinumCoinPile => ASH,
    BlockType::WeaponsRack => ANTIQUE_BRASS,
    BlockType::FireworksBox => TAN,
    BlockType::LivingFire => VERMILION,
    BlockType::AlphabetStatues => STACK,
    BlockType::FireworkFountain => MINT_GREEN,
    BlockType::GrasshopperCage => SPRAY,
    BlockType::LivingCursedFire => BRIGHT_GREEN,
    BlockType::LivingDemonFire => GOVERNOR_BAY,
    BlockType::LivingFrostFire => CYAN_AQUA,
    BlockType::LivingIchor => GOLDEN_TAINOI,
    BlockType::LivingUltrabrightFire => RIPTIDE,
    BlockType::Honeyfall => CALIFORNIA,
    BlockType::ChlorophyteBrick => CONIFER,
    BlockType::CrimtaneBrick => CARNATION,
    BlockType::ShroomitePlating => DARK_BLUE,
    BlockType::MushroomStatue => STACK,
    BlockType::MartianConduitPlating => SAN_MARINO,
    BlockType::ChimneySmoke => SHARK,
    BlockType::CrimtaneThorns => CARNATION,
    BlockType::VineRope => MALACHITE,
    BlockType::BewitchingTable => BEAVER,
    BlockType::AlchemyTable => BEAVER,
    BlockType::Sundial => GOLDEN_DREAM,
    BlockType::MarbleBlock => ROCK_BLUE,
    BlockType::GoldBirdCage => SPRAY,
    BlockType::GoldBunnyCage => SPRAY,
    BlockType::GoldButterflyCage => SPRAY,
    BlockType::GoldFrogCage => SPRAY,
    BlockType::GoldGrasshopperCage => SPRAY,
    BlockType::GoldMouseCage => SPRAY,
    BlockType::GoldWormCage => SPRAY,
    BlockType::SilkRope => DULL_LAVENDER,
    BlockType::WebRope => MYSTIC,
    BlockType::Marble => ROCK_BLUE,
    BlockType::Granite => JACARTA,
    BlockType::GraniteBlock => JACARTA,
    BlockType::MeteoriteBrick => CHETWODE_BLUE,
    BlockType::PinkSlimeBlock => HOT_PINK,
    BlockType::PeaceCandle => PERSIAN_PINK,
    BlockType::WaterDrip => PERSIAN_BLUE,
    BlockType::LavaDrip => SCARLET,
    BlockType::HoneyDrip => CALIFORNIA,
    BlockType::FishingCrate => LEATHER,
    BlockType::SharpeningStation => ANTIQUE_BRASS,
    BlockType::TargetDummy => LEATHER,
    BlockType::Bubble => CLASSIC_ROSE,
    BlockType::PlanterBox => ANTIQUE_BRASS,
    BlockType::LavaMoss => FLAMENCO,
    BlockType::VineFlowers => MALACHITE,
    BlockType::LivingMahogany => SEA_PINK,
    BlockType::LivingMahoganyLeaves => LIMA,
    BlockType::CrystalBlock => PIGMENT_INDIGO,
    BlockType::TrapdoorOpen => ROMAN_COFFEE,
    BlockType::TrapdoorClosed => ROMAN_COFFEE,
    BlockType::TallGateClosed => ROMAN_COFFEE,
    BlockType::TallGateOpen => ROMAN_COFFEE,
    BlockType::LavaLamp => SCARLET,
    BlockType::CageEnchantedNightcrawler => SPRAY,
    BlockType::CageBuggy => SPRAY,
    BlockType::CageGrubby => SPRAY,
    BlockType::CageSluggy => SPRAY,
    BlockType::ItemFrame => ANTIQUE_BRASS,
    BlockType::Sandstone => RAW_SIENNA,
    BlockType::HardenedSand => TACHA,
    BlockType::CorruptHardenedSand => KIMBERLY,
    BlockType::CrimsonHardenedSand => FUSCOUS_GRAY,
    BlockType::CorruptSandstone => BOSSANOVA,
    BlockType::CrimsonSandstone => ARMADILLO,
    BlockType::HallowHardenedSand => SPUN_PEARL,
    BlockType::HallowSandstone => VIOLA,
    BlockType::DesertFossil => POTTERS_CLAY,
    BlockType::Fireplace => GUNSMOKE,
    BlockType::Chimney => BOULDER,
    BlockType::FossilOre => GOLDEN_SAND,
    BlockType::LunarOre => FUSCOUS_GRAY,
    BlockType::LunarBrick => FUSCOUS_GRAY,
    BlockType::LunarMonolith => HORIZON,
    BlockType::Detonator => ALIZARIN_CRIMSON,
    BlockType::LunarCraftingStation => HORIZON,
    BlockType::SquirrelOrangeCage => SPRAY,
    BlockType::SquirrelGoldCage => SPRAY,
    BlockType::LunarBlockSolar => VERMILION,
    BlockType::LunarBlockVortex => EASTERN_BLUE,
    BlockType::LunarBlockNebula => PURPLE_HEART,
    BlockType::LunarBlockStardust => CURIOUS_BLUE,
    BlockType::LogicGateLamp => WATERLOO,
    BlockType::LogicGate => WHITE,
    BlockType::ConveyorBeltLeft => TUNDORA,
    BlockType::ConveyorBeltRight => TUNDORA,
    BlockType::LogicSensor => WHITE,
    BlockType::WirePipe => POLO_BLUE,
    BlockType::AnnouncementBox => CASPER,
    BlockType::TeamBlockRed => CASTRO,
    BlockType::TeamBlockRedPlatform => CLARET,
    BlockType::WeightedPressurePlate => WHITE,
    BlockType::WireBulb => MASALA,
    BlockType::TeamBlockGreen => JEWEL,
    BlockType::TeamBlockBlue => ASTRONAUT,
    BlockType::TeamBlockYellow => SEPIA,
    BlockType::TeamBlockPink => METEORITE,
    BlockType::TeamBlockWhite => COMET,
    BlockType::TeamBlockGreenPlatform => CHATEAU_GREEN,
    BlockType::TeamBlockBluePlatform => AZURE,
    BlockType::TeamBlockYellowPlatform => MANDALAY,
    BlockType::TeamBlockPinkPlatform => PURPLE,
    BlockType::TeamBlockWhitePlatform => AMETHYST_SMOKE,
    BlockType::GemLocks => WHITE,
    BlockType::FakeContainers => WHITE,
    BlockType::ProjectilePressurePad => CURIOUS_BLUE,
    BlockType::GeyserTrap => BOULDER,
    BlockType::BeeHive => STRAW,
    BlockType::PixelBox => TUNA,
    BlockType::SillyBalloonPink => WILD_STRAWBERRY,
    BlockType::SillyBalloonPurple => MEDIUM_PURPLE,
    BlockType::SillyBalloonGreen => PUERTO_RICO,
    BlockType::SillyStreamerBlue => PICTON_BLUE,
    BlockType::SillyStreamerGreen => SCREAMIN_GREEN,
    BlockType::SillyStreamerPink => FRENCH_ROSE,
    BlockType::SillyBalloonMachine => MAUVELOUS,
    BlockType::SillyBalloonTile => WHITE,
    BlockType::Pigronata => VIOLET_EGGPLANT,
    BlockType::PartyMonolith => SPRING_GREEN,
    BlockType::PartyBundleOfBalloonTile => MEDIUM_PURPLE,
    BlockType::PartyPresent => WHITE,
    BlockType::SandFallBlock => CHENIN,
    BlockType::SnowFallBlock => ZIGGURAT,
    BlockType::SnowCloud => BALI_HAI,
    BlockType::SandDrip => DANDELION,
    BlockType::DjinnLamp => GALLIANO,
    BlockType::DefendersForge => CORNFLOWER,
    BlockType::WarTable => TACAO,
    BlockType::WarTableBanner => CERULEAN_BLUE,
    BlockType::ElderCrystalStand => TUSSOCK,
    BlockType::Containers2 => GOLDENROD,
    BlockType::FakeContainers2 => WHITE,
    BlockType::Tables2 => ANTIQUE_BRASS,
  };
  pub static ref WALLTYPE_COLOR_MAP: HashMap<WallType, Rgba<i32>> = hashmap! {
    WallType::Stone => MINE_SHAFT,
    WallType::DirtUnsafe => MILLBROOK,
    WallType::EbonstoneUnsafe => GUN_POWDER,
    WallType::Wood => IROKO,
    WallType::GrayBrick => MINE_SHAFT,
    WallType::RedBrick => HEATH,
    WallType::BlueDungeonUnsafe => MIRAGE,
    WallType::GreenDungeonUnsafe => LOG_CABIN,
    WallType::PinkDungeonUnsafe => BASTILLE,
    WallType::GoldBrick => BRONZETONE,
    WallType::SilverBrick => OUTER_SPACE,
    WallType::CopperBrick => MOROCCO_BROWN,
    WallType::HellstoneBrickUnsafe => CRATER_BROWN,
    WallType::ObsidianBrickUnsafe => WOODSMOKE,
    WallType::MudUnsafe => THUNDER,
    WallType::Dirt => MILLBROOK,
    WallType::BlueDungeon => MIRAGE,
    WallType::GreenDungeon => LOG_CABIN,
    WallType::PinkDungeon => BASTILLE,
    WallType::ObsidianBrick => WOODSMOKE,
    WallType::Glass => BLACK,
    WallType::PearlstoneBrick => SCORPION,
    WallType::IridescentBrick => SHARK,
    WallType::MudstoneBrick => THUNDER,
    WallType::CobaltBrick => BIG_STONE,
    WallType::MythrilBrick => BLUE_DIANNE,
    WallType::Planked => MILLBROOK,
    WallType::PearlstoneBrickUnsafe => SCARPA_FLOW,
    WallType::CandyCane => HEATH,
    WallType::GreenCandyCane => CAMARONE,
    WallType::SnowBrick => TROUT,
    WallType::AdamantiteBeam => CASTRO,
    WallType::DemoniteBrick => MARTINIQUE,
    WallType::SandstoneBrick => LISBON_BROWN,
    WallType::EbonstoneBrick => TUNA,
    WallType::RedStucco => CONGO_BROWN,
    WallType::YellowStucco => LISBON_BROWN,
    WallType::GreenStucco => HEAVY_METAL,
    WallType::Gray => FUSCOUS_GRAY,
    WallType::SnowWallUnsafe => CORDUROY,
    WallType::Ebonwood => TUNA,
    WallType::RichMaogany => CRATER_BROWN,
    WallType::Pearlwood => MONDO,
    WallType::RainbowBrick => MINE_SHAFT,
    WallType::TinBrick => ARMADILLO,
    WallType::TungstenBrick => HEAVY_METAL,
    WallType::PlatinumBrick => ABBEY,
    WallType::AmethystUnsafe => MINE_SHAFT,
    WallType::TopazUnsafe => MINE_SHAFT,
    WallType::SapphireUnsafe => MINE_SHAFT,
    WallType::EmeraldUnsafe => MINE_SHAFT,
    WallType::RubyUnsafe => MINE_SHAFT,
    WallType::DiamondUnsafe => MINE_SHAFT,
    WallType::CaveUnsafe => HEAVY_METAL,
    WallType::Cave2unsafe => RANGITOTO,
    WallType::Cave3unsafe => COCOA_BROWN,
    WallType::Cave4unsafe => SHARK,
    WallType::Cave5unsafe => BLEACHED_CEDAR,
    WallType::Cave6unsafe => MILLBROOK,
    WallType::LivingLeaf => COUNTY_GREEN,
    WallType::Cave7unsafe => BISTRE,
    WallType::SpiderUnsafe => ZEUS,
    WallType::GrassUnsafe => ZUCCINI,
    WallType::JungleUnsafe => CLOVER,
    WallType::FlowerUnsafe => ZUCCINI,
    WallType::Grass => ZUCCINI,
    WallType::Jungle => CLOVER,
    WallType::Flower => ZUCCINI,
    WallType::CorruptGrassUnsafe => EBONY_CLAY,
    WallType::HallowedGrassUnsafe => BLUE_DIANNE,
    WallType::IceUnsafe => KASHMIR_BLUE,
    WallType::Cactus => GREEN_HOUSE,
    WallType::Cloud => PERIWINKLE_GRAY,
    WallType::Mushroom => GUN_POWDER,
    WallType::Bone => THATCH_GREEN,
    WallType::Slime => MADISON,
    WallType::Flesh => AUBERGINE,
    WallType::LivingWood => CORK,
    WallType::ObsidianBackUnsafe => BISCAY,
    WallType::MushroomUnsafe => GUN_POWDER,
    WallType::CrimsonGrassUnsafe => BUCCANEER,
    WallType::DiscWall => METALLIC_BRONZE,
    WallType::CrimstoneUnsafe => JON,
    WallType::IceBrick => BLUE_DIANNE,
    WallType::Shadewood => OUTER_SPACE,
    WallType::HiveUnsafe => RUSSET,
    WallType::LihzahrdBrickUnsafe => TAMARIND,
    WallType::PurpleStainedGlass => BLACK,
    WallType::YellowStainedGlass => BLACK,
    WallType::BlueStainedGlass => BLACK,
    WallType::GreenStainedGlass => BLACK,
    WallType::RedStainedGlass => BLACK,
    WallType::RainbowStainedGlass => BLACK,
    WallType::BlueDungeonSlabUnsafe => SHARK,
    WallType::BlueDungeonTileUnsafe => BALTIC_SEA,
    WallType::PinkDungeonSlabUnsafe => VOODOO,
    WallType::PinkDungeonTileUnsafe => EGGPLANT,
    WallType::GreenDungeonSlabUnsafe => MINE_SHAFT,
    WallType::GreenDungeonTileUnsafe => OUTER_SPACE,
    WallType::BlueDungeonSlab => SHARK,
    WallType::BlueDungeonTile => BALTIC_SEA,
    WallType::PinkDungeonSlab => VOODOO,
    WallType::PinkDungeonTile => EGGPLANT,
    WallType::GreenDungeonSlab => MINE_SHAFT,
    WallType::GreenDungeonTile => OUTER_SPACE,
    WallType::WoodenFence => BLACK,
    WallType::MetalFence => BLACK,
    WallType::Hive => RUSSET,
    WallType::PalladiumColumn => CHERRYWOOD,
    WallType::BubblegumBlock => PLUM,
    WallType::TitanstoneBlock => TREEHOUSE,
    WallType::LihzahrdBrick => TAMARIND,
    WallType::Pumpkin => PERU_TAN,
    WallType::Hay => MADRAS,
    WallType::SpookyWood => SHARK,
    WallType::ChristmasTreeWallpaper => HEATH,
    WallType::OrnamentWallpaper => FRIAR_GRAY,
    WallType::CandyCaneWallpaper => COUNTY_GREEN,
    WallType::FestiveWallpaper => HEATH,
    WallType::StarsWallpaper => BLUE_ZODIAC,
    WallType::SquigglesWallpaper => INDIAN_KHAKI,
    WallType::SnowflakeWallpaper => STORM_GRAY,
    WallType::KrampusHornWallpaper => HACIENDA,
    WallType::BluegreenWallpaper => DARK_FERN,
    WallType::GrinchFingerWallpaper => DINGLEY,
    WallType::FancyGrayWallpaper => SHUTTLE_GRAY,
    WallType::IceFloeWallpaper => MARINER,
    WallType::MusicWallpaper => CLAIRVOYANT,
    WallType::PurpleRainWallpaper => DAISY_BUSH,
    WallType::RainbowWallpaper => ULTRAMARINE,
    WallType::SparkleStoneWallpaper => COMET,
    WallType::StarlitHeavenWallpaper => COD_GRAY,
    WallType::BubbleWallpaper => GOVERNOR_BAY,
    WallType::CopperPipeWallpaper => RED_BEECH,
    WallType::DuckyWallpaper => DEEP_CERULEAN,
    WallType::Waterfall => ST_TROPAZ,
    WallType::Lavafall => VESUVIUS,
    WallType::EbonwoodFence => SCARPA_FLOW,
    WallType::RichMahoganyFence => BUCCANEER,
    WallType::PearlwoodFence => GO_BEN,
    WallType::ShadewoodFence => CAPE_COD,
    WallType::WhiteDynasty => JUNGLE_GREEN,
    WallType::BlueDynasty => CORDUROY,
    WallType::ArcaneRunes => GRAPE,
    WallType::IronFence => BLACK,
    WallType::CopperPlating => COPPER_CANYON,
    WallType::StoneSlab => TUATARA,
    WallType::Sail => ZOMBIE,
    WallType::BorealWood => TAUPE,
    WallType::BorealWoodFence => BLACK,
    WallType::PalmWood => DALLAS,
    WallType::PalmWoodFence => BLACK,
    WallType::AmberGemspark => JAFFA,
    WallType::AmethystGemspark => PINK_FLAMINGO,
    WallType::DiamondGemspark => ATHENS_GRAY,
    WallType::EmeraldGemspark => SCREAMIN_GREEN,
    WallType::AmberGemsparkOff => SEPIA_SKIN,
    WallType::AmethystGemsparkOff => ROYAL_PURPLE,
    WallType::DiamondGemsparkOff => COMET,
    WallType::EmeraldGemsparkOff => CHATEAU_GREEN,
    WallType::RubyGemsparkOff => NIGHT_SHADZ,
    WallType::SapphireGemsparkOff => SMALT,
    WallType::TopazGemsparkOff => SYCAMORE,
    WallType::RubyGemspark => SUNSET_ORANGE,
    WallType::SapphireGemspark => BLUE_RIBBON,
    WallType::TopazGemspark => GOLDEN_FIZZ,
    WallType::TinPlating => KELP,
    WallType::Confetti => BLACK,
    WallType::ConfettiBlack => BLACK,
    WallType::CaveWall => BLACK_MARLIN,
    WallType::CaveWall2 => BLACK_MARLIN,
    WallType::Honeyfall => RENO_SAND,
    WallType::ChlorophyteBrick => VIDA_LOCA,
    WallType::CrimtaneBrick => BLACK_ROSE,
    WallType::ShroomitePlating => DARK_BLUE,
    WallType::MartianConduit => GUN_POWDER,
    WallType::HellstoneBrick => JON,
    WallType::MarbleUnsafe => STORM_GRAY,
    WallType::MarbleBlock => STORM_GRAY,
    WallType::GraniteUnsafe => HAITI,
    WallType::GraniteBlock => HAITI,
    WallType::MeteoriteBrick => EAST_BAY,
    WallType::Marble => STORM_GRAY,
    WallType::Granite => HAITI,
    WallType::Cave8unsafe => MINE_SHAFT,
    WallType::Crystal => VIOLET,
    WallType::Sandstone => MULE_FAWN,
    WallType::CorruptionUnsafe1 => MORTAR,
    WallType::CorruptionUnsafe2 => BRIGHT_GRAY,
    WallType::CorruptionUnsafe3 => GUN_POWDER,
    WallType::CorruptionUnsafe4 => VOODOO,
    WallType::CrimsonUnsafe1 => EL_SALVA,
    WallType::CrimsonUnsafe2 => STILETTO,
    WallType::CrimsonUnsafe3 => PERSIAN_PLUM,
    WallType::CrimsonUnsafe4 => STILETTO,
    WallType::DirtUnsafe1 => QUINCY,
    WallType::DirtUnsafe2 => ROMAN_COFFEE,
    WallType::DirtUnsafe3 => MILLBROOK,
    WallType::DirtUnsafe4 => ROMAN_COFFEE,
    WallType::HallowUnsafe1 => PLUM,
    WallType::HallowUnsafe2 => MAMBA,
    WallType::HallowUnsafe3 => CRANBERRY,
    WallType::HallowUnsafe4 => AFFAIR,
    WallType::JungleUnsafe1 => ARMADILLO,
    WallType::JungleUnsafe2 => CABBAGE_PONT,
    WallType::JungleUnsafe3 => COUNTY_GREEN,
    WallType::JungleUnsafe4 => AXOLOTL,
    WallType::LavaUnsafe1 => SHARK,
    WallType::LavaUnsafe2 => TUNDORA,
    WallType::LavaUnsafe3 => LONESTAR,
    WallType::LavaUnsafe4 => KABUL,
    WallType::RocksUnsafe1 => FUSCOUS_GRAY,
    WallType::RocksUnsafe2 => CAPE_COD,
    WallType::RocksUnsafe3 => MATTERHORN,
    WallType::RocksUnsafe4 => LIVID_BROWN,
    WallType::HardenedSand => CAPE_PALLISER,
    WallType::CorruptHardenedSand => MARTINIQUE,
    WallType::CrimsonHardenedSand => AUBERGINE,
    WallType::HallowHardenedSand => BUTTERFLY_BUSH,
    WallType::CorruptSandstone => MARTINIQUE,
    WallType::CrimsonSandstone => CORK,
    WallType::HallowSandstone => VOODOO,
    WallType::DesertFossil => CEDAR,
    WallType::LunarBrickWall => DUNE,
    WallType::CogWall => CAPE_COD,
    WallType::SandFall => PESTO,
    WallType::SnowFall => DANUBE,
    WallType::SillyBalloonPinkWall => JAZZBERRY_JAM,
    WallType::SillyBalloonPurpleWall => ROYAL_PURPLE,
    WallType::SillyBalloonGreenWall => PINE_GREEN,
  };
  pub static ref PAINT_COLOR_MAP: HashMap<u8, Rgba<i32>> = hashmap! {
    0 => BLACK,
    1 => RED,
    2 => FLUSH_ORANGE,
    3 => YELLOW,
    4 => CHARTREUSE,
    5 => GREEN,
    6 => SPRING_GREEN,
    7 => CYAN_AQUA,
    8 => AZURE_RADIANCE,
    9 => BLUE,
    10 => ELECTRIC_VIOLET,
    11 => MAGENTA_FUCHSIA,
    12 => ROSE,
    13 => RED,
    14 => FLUSH_ORANGE,
    15 => YELLOW,
    16 => CHARTREUSE,
    17 => GREEN,
    18 => SPRING_GREEN,
    19 => CYAN_AQUA,
    20 => AZURE_RADIANCE,
    21 => BLUE,
    22 => ELECTRIC_VIOLET,
    23 => MAGENTA_FUCHSIA,
    24 => ROSE,
    25 => ABBEY,
    26 => WHITE,
    27 => SILVER_CHALICE,
    28 => MACARONI_AND_CHEESE,
    29 => WOODSMOKE,
    30 => SILVER_SAND
  };
}

pub const SPACE_COLOR: Rgba<i32> = MATISSE;
pub const SKY_COLOR: Rgba<i32> = MALIBU;
pub const UNDERGROUND_COLOR: Rgba<i32> = SADDLE;
pub const CAVERNS_COLOR: Rgba<i32> = ARMADILLO;
pub const HELL_COLOR: Rgba<i32> = CHOCOLATE;
pub const LAVA_COLOR: Rgba<i32> = SCARLET;
pub const HONEY_COLOR: Rgba<i32> = YELLOW_SEA;
pub const WATER_COLOR: Rgba<i32> = BLUE;
pub const RED_WIRE_COLOR: Rgba<i32> = RED;
pub const BLUE_WIRE_COLOR: Rgba<i32> = BLUE;
pub const GREEN_WIRE_COLOR: Rgba<i32> = GREEN;
pub const YELLOW_WIRE_COLOR: Rgba<i32> = YELLOW;
