use crate::enums::{
  BlockType,
  WallType,
};
use fnv::FnvHashMap;
use image::Rgba;

pub const ABBEY: Rgba<u8> = Rgba([76, 74, 83, 255]);
pub const AFFAIR: Rgba<u8> = Rgba([113, 64, 150, 255]);
pub const ALIZARIN_CRIMSON: Rgba<u8> = Rgba([231, 53, 56, 255]);
pub const AMETHYST_SMOKE: Rgba<u8> = Rgba([147, 144, 178, 255]);
pub const AMULET: Rgba<u8> = Rgba([132, 157, 127, 255]);
pub const ANTIQUE_BRASS: Rgba<u8> = Rgba([191, 142, 111, 255]);
pub const APPLE: Rgba<u8> = Rgba([23, 177, 76, 255]);
pub const ARMADILLO: Rgba<u8> = Rgba([62, 61, 52, 255]);
pub const ASH: Rgba<u8> = Rgba([190, 190, 178, 255]);
pub const ASTRONAUT: Rgba<u8> = Rgba([23, 54, 119, 255]);
pub const ATHENS_GRAY: Rgba<u8> = Rgba([240, 240, 247, 255]);
pub const ATLANTIS: Rgba<u8> = Rgba([143, 215, 29, 255]);
pub const AUBERGINE: Rgba<u8> = Rgba([61, 13, 16, 255]);
pub const AU_CHICO: Rgba<u8> = Rgba([145, 81, 85, 255]);
pub const AVOCADO: Rgba<u8> = Rgba([157, 157, 107, 255]);
pub const AXOLOTL: Rgba<u8> = Rgba([84, 100, 63, 255]);
pub const AZURE: Rgba<u8> = Rgba([39, 94, 168, 255]);
pub const AZURE_RADIANCE: Rgba<u8> = Rgba([93, 127, 255, 255]);
pub const BABY_BLUE: Rgba<u8> = Rgba([223, 255, 255, 255]);
pub const BALI_HAI: Rgba<u8> = Rgba([141, 163, 181, 255]);
pub const BALTIC_SEA: Rgba<u8> = Rgba([44, 41, 50, 255]);
pub const BASTILLE: Rgba<u8> = Rgba([41, 28, 36, 255]);
pub const BEAVER: Rgba<u8> = Rgba([140, 101, 80, 255]);
pub const BIG_STONE: Rgba<u8> = Rgba([11, 35, 62, 255]);
pub const BISCAY: Rgba<u8> = Rgba([51, 47, 96, 255]);
pub const BISTRE: Rgba<u8> = Rgba([55, 39, 26, 255]);
pub const BIZARRE: Rgba<u8> = Rgba([238, 225, 218, 255]);
pub const BLACK: Rgba<u8> = Rgba([0, 0, 0, 0]);
pub const BLACK_MARLIN: Rgba<u8> = Rgba([59, 39, 22, 255]);
pub const BLACK_ROSE: Rgba<u8> = Rgba([117, 32, 59, 255]);
pub const BLEACHED_CEDAR: Rgba<u8> = Rgba([48, 35, 52, 255]);
pub const BLUE: Rgba<u8> = Rgba([0, 12, 255, 128]);
pub const BLUE_BELL: Rgba<u8> = Rgba([151, 135, 183, 255]);
pub const BLUE_DIANNE: Rgba<u8> = Rgba([21, 63, 70, 255]);
pub const BLUE_RIBBON: Rgba<u8> = Rgba([79, 102, 255, 255]);
pub const BLUE_ZODIAC: Rgba<u8> = Rgba([17, 31, 65, 255]);
pub const BLUSH_PINK: Rgba<u8> = Rgba([231, 96, 228, 255]);
pub const BOSSANOVA: Rgba<u8> = Rgba([96, 68, 117, 255]);
pub const BOULDER: Rgba<u8> = Rgba([120, 120, 120, 255]);
pub const BREAKER_BAY: Rgba<u8> = Rgba([91, 169, 169, 255]);
pub const BRIGHT_GRAY: Rgba<u8> = Rgba([65, 61, 77, 255]);
pub const BRIGHT_GREEN: Rgba<u8> = Rgba([96, 248, 2, 255]);
pub const BRIGHT_SUN: Rgba<u8> = Rgba([255, 218, 56, 255]);
pub const BRONZETONE: Rgba<u8> = Rgba([74, 62, 12, 255]);
pub const BROOM: Rgba<u8> = Rgba([255, 241, 51, 255]);
pub const BUCCANEER: Rgba<u8> = Rgba([101, 51, 51, 255]);
pub const BUD: Rgba<u8> = Rgba([170, 171, 157, 255]);
pub const BURNT_SIENNA: Rgba<u8> = Rgba([235, 114, 80, 255]);
pub const BUTTERFLY_BUSH: Rgba<u8> = Rgba([96, 72, 133, 255]);
pub const CABBAGE_PONT: Rgba<u8> = Rgba([60, 78, 59, 255]);
pub const CADILLAC: Rgba<u8> = Rgba([196, 96, 114, 255]);
pub const CALIFORNIA: Rgba<u8> = Rgba([255, 156, 12, 255]);
pub const CAMARONE: Rgba<u8> = Rgba([28, 88, 23, 255]);
pub const CAPE_COD: Rgba<u8> = Rgba([59, 67, 71, 255]);
pub const CAPE_PALLISER: Rgba<u8> = Rgba([163, 116, 81, 255]);
pub const CARNATION: Rgba<u8> = Rgba([230, 89, 92, 255]);
pub const CASPER: Rgba<u8> = Rgba([181, 194, 217, 255]);
pub const CASTRO: Rgba<u8> = Rgba([77, 11, 35, 255]);
pub const CEDAR: Rgba<u8> = Rgba([51, 18, 4, 255]);
pub const CERULEAN_BLUE: Rgba<u8> = Rgba([51, 84, 195, 255]);
pub const CHARTREUSE: Rgba<u8> = Rgba([127, 255, 0, 255]);
pub const CHATEAU_GREEN: Rgba<u8> = Rgba([49, 154, 68, 255]);
pub const CHATELLE: Rgba<u8> = Rgba([181, 172, 190, 255]);
pub const CHENIN: Rgba<u8> = Rgba([211, 198, 111, 255]);
pub const CHERRYWOOD: Rgba<u8> = Rgba([94, 25, 17, 255]);
pub const CHETWODE_BLUE: Rgba<u8> = Rgba([141, 137, 223, 255]);
pub const CHOCOLATE: Rgba<u8> = Rgba([51, 0, 0, 255]);
pub const CHRISTI: Rgba<u8> = Rgba([121, 176, 24, 255]);
pub const CINNABAR: Rgba<u8> = Rgba([220, 50, 50, 255]);
pub const CLAIRVOYANT: Rgba<u8> = Rgba([93, 6, 102, 255]);
pub const CLARET: Rgba<u8> = Rgba([128, 26, 52, 255]);
pub const CLASSIC_ROSE: Rgba<u8> = Rgba([251, 209, 240, 255]);
pub const CLAY_CREEK: Rgba<u8> = Rgba([148, 133, 98, 255]);
pub const CLOVER: Rgba<u8> = Rgba([53, 80, 30, 255]);
pub const COCOA_BROWN: Rgba<u8> = Rgba([43, 33, 32, 255]);
pub const COD_GRAY: Rgba<u8> = Rgba([6, 6, 6, 255]);
pub const COMET: Rgba<u8> = Rgba([85, 89, 118, 255]);
pub const CONGO_BROWN: Rgba<u8> = Rgba([87, 59, 55, 255]);
pub const CONIFER: Rgba<u8> = Rgba([149, 232, 87, 255]);
pub const COPPER_CANYON: Rgba<u8> = Rgba([120, 59, 19, 255]);
pub const COPPER_RUST: Rgba<u8> = Rgba([151, 79, 80, 255]);
pub const CORDUROY: Rgba<u8> = Rgba([85, 102, 103, 255]);
pub const CORK: Rgba<u8> = Rgba([63, 39, 26, 255]);
pub const CORNFLOWER: Rgba<u8> = Rgba([144, 195, 232, 255]);
pub const COUNTY_GREEN: Rgba<u8> = Rgba([1, 52, 20, 255]);
pub const CRAIL: Rgba<u8> = Rgba([204, 93, 73, 255]);
pub const CRANBERRY: Rgba<u8> = Rgba([219, 92, 143, 255]);
pub const CRATER_BROWN: Rgba<u8> = Rgba([67, 37, 37, 255]);
pub const CROWN_OF_THORNS: Rgba<u8> = Rgba([128, 44, 45, 255]);
pub const CUMIN: Rgba<u8> = Rgba([150, 67, 22, 255]);
pub const CURIOUS_BLUE: Rgba<u8> = Rgba([22, 173, 254, 255]);
pub const CYAN_AQUA: Rgba<u8> = Rgba([29, 240, 255, 255]);
pub const DAISY_BUSH: Rgba<u8> = Rgba([64, 40, 169, 255]);
pub const DALLAS: Rgba<u8> = Rgba([102, 75, 34, 255]);
pub const DANDELION: Rgba<u8> = Rgba([255, 222, 100, 255]);
pub const DANUBE: Rgba<u8> = Rgba([95, 137, 191, 255]);
pub const DARK_BLUE: Rgba<u8> = Rgba([0, 0, 200, 255]);
pub const DARK_FERN: Rgba<u8> = Rgba([8, 72, 3, 255]);
pub const DEEP_CERULEAN: Rgba<u8> = Rgba([22, 123, 163, 255]);
pub const DINGLEY: Rgba<u8> = Rgba([117, 132, 82, 255]);
pub const DIXIE: Rgba<u8> = Rgba([235, 150, 23, 255]);
pub const DODGER_BLUE: Rgba<u8> = Rgba([43, 143, 255, 255]);
pub const DOLPHIN: Rgba<u8> = Rgba([103, 98, 122, 255]);
pub const DON_JUAN: Rgba<u8> = Rgba([92, 68, 73, 255]);
pub const DORADO: Rgba<u8> = Rgba([104, 86, 84, 255]);
pub const DRIFTWOOD: Rgba<u8> = Rgba([160, 118, 58, 255]);
pub const DULL_LAVENDER: Rgba<u8> = Rgba([146, 136, 205, 255]);
pub const DUNE: Rgba<u8> = Rgba([53, 44, 41, 255]);
pub const EASTERN_BLUE: Rgba<u8> = Rgba([0, 160, 170, 255]);
pub const EAST_BAY: Rgba<u8> = Rgba([74, 71, 129, 255]);
pub const EAST_SIDE: Rgba<u8> = Rgba([174, 145, 214, 255]);
pub const EBONY_CLAY: Rgba<u8> = Rgba([43, 42, 68, 255]);
pub const EDWARD: Rgba<u8> = Rgba([161, 172, 173, 255]);
pub const EGGPLANT: Rgba<u8> = Rgba([78, 50, 69, 255]);
pub const ELECTRIC_VIOLET: Rgba<u8> = Rgba([127, 0, 255, 255]);
pub const EL_SALVA: Rgba<u8> = Rgba([144, 67, 52, 255]);
pub const EMERALD: Rgba<u8> = Rgba([27, 197, 109, 255]);
pub const EQUATOR: Rgba<u8> = Rgba([224, 194, 101, 255]);
pub const FIORD: Rgba<u8> = Rgba([66, 84, 109, 255]);
pub const FLAMENCO: Rgba<u8> = Rgba([255, 120, 0, 255]);
pub const FLAMINGO: Rgba<u8> = Rgba([239, 90, 50, 255]);
pub const FLUSH_MAHOGANY: Rgba<u8> = Rgba([203, 61, 64, 255]);
pub const FLUSH_ORANGE: Rgba<u8> = Rgba([255, 127, 0, 255]);
pub const FRENCH_ROSE: Rgba<u8> = Rgba([240, 91, 147, 255]);
pub const FRIAR_GRAY: Rgba<u8> = Rgba([126, 123, 115, 255]);
pub const FUSCOUS_GRAY: Rgba<u8> = Rgba([77, 74, 72, 255]);
pub const GALLIANO: Rgba<u8> = Rgba([213, 178, 28, 255]);
pub const GEYSER: Rgba<u8> = Rgba([213, 229, 237, 255]);
pub const GLACIER: Rgba<u8> = Rgba([124, 175, 201, 255]);
pub const GOLDENROD: Rgba<u8> = Rgba([233, 207, 94, 255]);
pub const GOLDEN_DREAM: Rgba<u8> = Rgba([233, 203, 24, 255]);
pub const GOLDEN_FIZZ: Rgba<u8> = Rgba([250, 255, 79, 255]);
pub const GOLDEN_SAND: Rgba<u8> = Rgba([255, 227, 132, 255]);
pub const GOLDEN_TAINOI: Rgba<u8> = Rgba([254, 202, 80, 255]);
pub const GOLD_TIPS: Rgba<u8> = Rgba([226, 196, 49, 255]);
pub const GOVERNOR_BAY: Rgba<u8> = Rgba([105, 74, 202, 255]);
pub const GO_BEN: Rgba<u8> = Rgba([119, 108, 81, 255]);
pub const GRANNY_SMITH: Rgba<u8> = Rgba([131, 162, 161, 255]);
pub const GRAPE: Rgba<u8> = Rgba([62, 28, 87, 255]);
pub const GRAVEL: Rgba<u8> = Rgba([68, 68, 76, 255]);
pub const GRAY: Rgba<u8> = Rgba([128, 128, 128, 255]);
pub const GREEN: Rgba<u8> = Rgba([0, 255, 0, 112]);
pub const GREEN_HOUSE: Rgba<u8> = Rgba([52, 84, 12, 255]);
pub const GREEN_LEAF: Rgba<u8> = Rgba([73, 120, 17, 255]);
pub const GUNSMOKE: Rgba<u8> = Rgba([140, 140, 140, 255]);
pub const GUN_POWDER: Rgba<u8> = Rgba([61, 58, 78, 255]);
pub const GURKHA: Rgba<u8> = Rgba([149, 149, 115, 255]);
pub const HACIENDA: Rgba<u8> = Rgba([136, 119, 7, 255]);
pub const HAITI: Rgba<u8> = Rgba([25, 23, 54, 255]);
pub const HALF_BAKED: Rgba<u8> = Rgba([125, 191, 197, 255]);
pub const HAMPTON: Rgba<u8> = Rgba([228, 213, 173, 255]);
pub const HEATH: Rgba<u8> = Rgba([91, 30, 30, 255]);
pub const HEAVY_METAL: Rgba<u8> = Rgba([49, 57, 49, 255]);
pub const HORIZON: Rgba<u8> = Rgba([75, 139, 166, 255]);
pub const HOT_PINK: Rgba<u8> = Rgba([249, 101, 189, 255]);
pub const HUSK: Rgba<u8> = Rgba([190, 171, 94, 255]);
pub const INDIAN_KHAKI: Rgba<u8> = Rgba([203, 185, 151, 255]);
pub const IROKO: Rgba<u8> = Rgba([73, 51, 36, 255]);
pub const IRONSTONE: Rgba<u8> = Rgba([146, 81, 68, 255]);
pub const JACARTA: Rgba<u8> = Rgba([50, 46, 104, 255]);
pub const JAFFA: Rgba<u8> = Rgba([255, 145, 79, 255]);
pub const JAMBALAYA: Rgba<u8> = Rgba([99, 50, 30, 255]);
pub const JAZZBERRY_JAM: Rgba<u8> = Rgba([160, 2, 75, 255]);
pub const JET_STREAM: Rgba<u8> = Rgba([181, 211, 210, 255]);
pub const JEWEL: Rgba<u8> = Rgba([23, 119, 79, 255]);
pub const JON: Rgba<u8> = Rgba([62, 38, 41, 255]);
pub const JUNGLE_GREEN: Rgba<u8> = Rgba([17, 172, 143, 255]);
pub const KABUL: Rgba<u8> = Rgba([96, 77, 64, 255]);
pub const KASHMIR_BLUE: Rgba<u8> = Rgba([78, 105, 135, 255]);
pub const KELP: Rgba<u8> = Rgba([70, 68, 51, 255]);
pub const KIMBERLY: Rgba<u8> = Rgba([100, 82, 126, 255]);
pub const KOURNIKOVA: Rgba<u8> = Rgba([251, 235, 127, 255]);
pub const LAVENDER_MAGENTA: Rgba<u8> = Rgba([255, 117, 224, 255]);
pub const LAVENDER_PURPLE: Rgba<u8> = Rgba([141, 120, 168, 255]);
pub const LAVENDER_ROSE: Rgba<u8> = Rgba([225, 128, 206, 255]);
pub const LEATHER: Rgba<u8> = Rgba([151, 107, 75, 255]);
pub const LIMA: Rgba<u8> = Rgba([96, 197, 27, 255]);
pub const LISBON_BROWN: Rgba<u8> = Rgba([69, 67, 41, 255]);
pub const LIVID_BROWN: Rgba<u8> = Rgba([89, 48, 59, 255]);
pub const LOG_CABIN: Rgba<u8> = Rgba([31, 39, 26, 255]);
pub const LONESTAR: Rgba<u8> = Rgba([111, 6, 6, 255]);
pub const LUXOR_GOLD: Rgba<u8> = Rgba([153, 131, 44, 255]);
pub const MABEL: Rgba<u8> = Rgba([211, 236, 241, 255]);
pub const MACARONI_AND_CHEESE: Rgba<u8> = Rgba([255, 178, 125, 255]);
pub const MADISON: Rgba<u8> = Rgba([20, 46, 104, 255]);
pub const MADRAS: Rgba<u8> = Rgba([65, 52, 15, 255]);
pub const MAGENTA_FUCHSIA: Rgba<u8> = Rgba([255, 0, 255, 255]);
pub const MALACHITE: Rgba<u8> = Rgba([28, 216, 94, 255]);
pub const MALIBU: Rgba<u8> = Rgba([155, 209, 255, 255]);
pub const MAMBA: Rgba<u8> = Rgba([136, 120, 131, 255]);
pub const MANDALAY: Rgba<u8> = Rgba([168, 121, 39, 255]);
pub const MARINER: Rgba<u8> = Rgba([30, 118, 226, 255]);
pub const MAROON_FLUSH: Rgba<u8> = Rgba([174, 24, 69, 255]);
pub const MARTINIQUE: Rgba<u8> = Rgba([49, 47, 83, 255]);
pub const MASALA: Rgba<u8> = Rgba([63, 63, 63, 255]);
pub const MATISSE: Rgba<u8> = Rgba([51, 102, 153, 255]);
pub const MATTERHORN: Rgba<u8> = Rgba([76, 52, 60, 255]);
pub const MAUVELOUS: Rgba<u8> = Rgba([255, 150, 181, 255]);
pub const MEDIUM_CARMINE: Rgba<u8> = Rgba([181, 62, 59, 255]);
pub const MEDIUM_PURPLE: Rgba<u8> = Rgba([179, 132, 255, 255]);
pub const MELANIE: Rgba<u8> = Rgba([218, 182, 204, 255]);
pub const MERLOT: Rgba<u8> = Rgba([134, 22, 34, 255]);
pub const METALLIC_BRONZE: Rgba<u8> = Rgba([77, 64, 34, 255]);
pub const METEORITE: Rgba<u8> = Rgba([74, 23, 119, 255]);
pub const MILLBROOK: Rgba<u8> = Rgba([88, 61, 46, 255]);
pub const MINE_SHAFT: Rgba<u8> = Rgba([52, 52, 52, 255]);
pub const MINT_GREEN: Rgba<u8> = Rgba([85, 255, 160, 255]);
pub const MIRAGE: Rgba<u8> = Rgba([27, 31, 42, 255]);
pub const MONDO: Rgba<u8> = Rgba([73, 66, 50, 255]);
pub const MONGOOSE: Rgba<u8> = Rgba([181, 164, 125, 255]);
pub const MOROCCO_BROWN: Rgba<u8> = Rgba([75, 32, 11, 255]);
pub const MORTAR: Rgba<u8> = Rgba([82, 63, 80, 255]);
pub const MOUNTAIN_MEADOW: Rgba<u8> = Rgba([48, 186, 135, 255]);
pub const MOUNTAIN_MIST: Rgba<u8> = Rgba([144, 144, 144, 255]);
pub const MULE_FAWN: Rgba<u8> = Rgba([149, 80, 51, 255]);
pub const MYSTIC: Rgba<u8> = Rgba([223, 232, 233, 255]);
pub const NIGHT_SHADZ: Rgba<u8> = Rgba([154, 49, 77, 255]);
pub const NORWAY: Rgba<u8> = Rgba([166, 187, 153, 255]);
pub const OLD_GOLD: Rgba<u8> = Rgba([214, 184, 46, 255]);
pub const OLD_LAVENDER: Rgba<u8> = Rgba([119, 101, 125, 255]);
pub const ONAHAU: Rgba<u8> = Rgba([200, 246, 254, 255]);
pub const OREGON: Rgba<u8> = Rgba([141, 56, 0, 255]);
pub const OSLO_GRAY: Rgba<u8> = Rgba([140, 150, 150, 255]);
pub const OUTER_SPACE: Rgba<u8> = Rgba([46, 56, 59, 255]);
pub const PABLO: Rgba<u8> = Rgba([121, 119, 101, 255]);
pub const PACIFIC_BLUE: Rgba<u8> = Rgba([33, 171, 207, 255]);
pub const PACIFIKA: Rgba<u8> = Rgba([126, 134, 49, 255]);
pub const PEAT: Rgba<u8> = Rgba([119, 105, 79, 255]);
pub const PERIWINKLE_GRAY: Rgba<u8> = Rgba([190, 204, 223, 255]);
pub const PERSIAN_BLUE: Rgba<u8> = Rgba([9, 61, 191, 255]);
pub const PERSIAN_PINK: Rgba<u8> = Rgba([245, 133, 191, 255]);
pub const PERSIAN_PLUM: Rgba<u8> = Rgba([111, 32, 36, 255]);
pub const PERU_TAN: Rgba<u8> = Rgba([135, 58, 0, 255]);
pub const PESTO: Rgba<u8> = Rgba([137, 120, 67, 255]);
pub const PETITE_ORCHID: Rgba<u8> = Rgba([216, 152, 144, 255]);
pub const PICTON_BLUE: Rgba<u8> = Rgba([91, 186, 240, 255]);
pub const PIGMENT_INDIGO: Rgba<u8> = Rgba([87, 21, 144, 255]);
pub const PINE_GREEN: Rgba<u8> = Rgba([0, 117, 101, 255]);
pub const PINK_FLAMINGO: Rgba<u8> = Rgba([221, 79, 255, 255]);
pub const PLUM: Rgba<u8> = Rgba([125, 36, 122, 255]);
pub const POLO_BLUE: Rgba<u8> = Rgba([146, 155, 187, 255]);
pub const PORTAGE: Rgba<u8> = Rgba([141, 175, 255, 255]);
pub const PORT_GORE: Rgba<u8> = Rgba([43, 40, 84, 255]);
pub const POTTERS_CLAY: Rgba<u8> = Rgba([140, 84, 60, 255]);
pub const PUERTO_RICO: Rgba<u8> = Rgba([0, 206, 180, 255]);
pub const PUNCH: Rgba<u8> = Rgba([219, 71, 38, 255]);
pub const PURPLE: Rgba<u8> = Rgba([111, 39, 168, 255]);
pub const PURPLE_HEART: Rgba<u8> = Rgba([160, 87, 234, 255]);
pub const QUINCY: Rgba<u8> = Rgba([96, 68, 48, 255]);
pub const RANGITOTO: Rgba<u8> = Rgba([49, 48, 36, 255]);
pub const RAW_SIENNA: Rgba<u8> = Rgba([198, 124, 78, 255]);
pub const RED: Rgba<u8> = Rgba([255, 0, 0, 112]);
pub const RED_BEECH: Rgba<u8> = Rgba([130, 62, 16, 255]);
pub const REGENT_ST_BLUE: Rgba<u8> = Rgba([159, 209, 229, 255]);
pub const RENO_SAND: Rgba<u8> = Rgba([163, 96, 0, 255]);
pub const RIPTIDE: Rgba<u8> = Rgba([131, 252, 245, 255]);
pub const ROCK_BLUE: Rgba<u8> = Rgba([152, 171, 198, 255]);
pub const ROMAN: Rgba<u8> = Rgba([208, 80, 80, 255]);
pub const ROMAN_COFFEE: Rgba<u8> = Rgba([127, 92, 69, 255]);
pub const ROSE: Rgba<u8> = Rgba([255, 0, 127, 255]);
pub const ROYAL_HEATH: Rgba<u8> = Rgba([170, 48, 114, 255]);
pub const ROYAL_PURPLE: Rgba<u8> = Rgba([107, 49, 154, 255]);
pub const RUM: Rgba<u8> = Rgba([109, 90, 128, 255]);
pub const RUSSET: Rgba<u8> = Rgba([138, 73, 38, 255]);
pub const RUSTY_NAIL: Rgba<u8> = Rgba([131, 79, 13, 255]);
pub const SADDLE: Rgba<u8> = Rgba([84, 57, 42, 255]);
pub const SAHARA: Rgba<u8> = Rgba([185, 164, 23, 255]);
pub const SAIL: Rgba<u8> = Rgba([184, 219, 240, 255]);
pub const SALT_BOX: Rgba<u8> = Rgba([107, 92, 108, 255]);
pub const SANDSTONE: Rgba<u8> = Rgba([121, 110, 97, 255]);
pub const SANGUINE_BROWN: Rgba<u8> = Rgba([134, 59, 49, 255]);
pub const SAN_JUAN: Rgba<u8> = Rgba([62, 82, 114, 255]);
pub const SAN_MARINO: Rgba<u8> = Rgba([55, 97, 155, 255]);
pub const SCAMPI: Rgba<u8> = Rgba([98, 95, 167, 255]);
pub const SCARLET: Rgba<u8> = Rgba([253, 32, 3, 255]);
pub const SCARPA_FLOW: Rgba<u8> = Rgba([81, 84, 101, 255]);
pub const SCHOOL_BUS_YELLOW: Rgba<u8> = Rgba([253, 221, 3, 255]);
pub const SCOOTER: Rgba<u8> = Rgba([48, 208, 234, 255]);
pub const SCORPION: Rgba<u8> = Rgba([113, 99, 99, 255]);
pub const SCREAMIN_GREEN: Rgba<u8> = Rgba([79, 255, 89, 255]);
pub const SEAGULL: Rgba<u8> = Rgba([133, 213, 247, 255]);
pub const SEANCE: Rgba<u8> = Rgba([140, 58, 166, 255]);
pub const SEA_GREEN: Rgba<u8> = Rgba([56, 150, 97, 255]);
pub const SEA_PINK: Rgba<u8> = Rgba([221, 136, 144, 255]);
pub const SEPIA: Rgba<u8> = Rgba([119, 68, 23, 255]);
pub const SEPIA_SKIN: Rgba<u8> = Rgba([154, 83, 49, 255]);
pub const SHARK: Rgba<u8> = Rgba([36, 36, 36, 255]);
pub const SHIP_COVE: Rgba<u8> = Rgba([110, 140, 182, 255]);
pub const SHUTTLE_GRAY: Rgba<u8> = Rgba([106, 107, 118, 255]);
pub const SILVER: Rgba<u8> = Rgba([192, 192, 192, 255]);
pub const SILVER_CHALICE: Rgba<u8> = Rgba([175, 175, 175, 255]);
pub const SILVER_SAND: Rgba<u8> = Rgba([200, 200, 200, 150]);
pub const SIROCCO: Rgba<u8> = Rgba([107, 132, 139, 255]);
pub const SMALT: Rgba<u8> = Rgba([49, 49, 154, 255]);
pub const SOLID_PINK: Rgba<u8> = Rgba([125, 55, 65, 255]);
pub const SORRELL_BROWN: Rgba<u8> = Rgba([182, 175, 130, 255]);
pub const SPRAY: Rgba<u8> = Rgba([122, 217, 232, 255]);
pub const SPRING_GREEN: Rgba<u8> = Rgba([48, 255, 110, 255]);
pub const SPUN_PEARL: Rgba<u8> = Rgba([174, 168, 186, 255]);
pub const SQUIRREL: Rgba<u8> = Rgba([140, 130, 116, 255]);
pub const STACK: Rgba<u8> = Rgba([144, 148, 144, 255]);
pub const STAR_DUST: Rgba<u8> = Rgba([160, 160, 160, 255]);
pub const STILETTO: Rgba<u8> = Rgba([149, 48, 48, 255]);
pub const STORM_DUST: Rgba<u8> = Rgba([96, 96, 96, 255]);
pub const STORM_GRAY: Rgba<u8> = Rgba([114, 114, 131, 255]);
pub const STRAW: Rgba<u8> = Rgba([191, 176, 124, 255]);
pub const ST_TROPAZ: Rgba<u8> = Rgba([11, 80, 143, 255]);
pub const SUBMARINE: Rgba<u8> = Rgba([185, 194, 195, 255]);
pub const SULU: Rgba<u8> = Rgba([191, 233, 115, 255]);
pub const SUNGLO: Rgba<u8> = Rgba([253, 114, 114, 255]);
pub const SUNSET_ORANGE: Rgba<u8> = Rgba([255, 79, 79, 255]);
pub const SWISS_COFFEE: Rgba<u8> = Rgba([213, 203, 204, 255]);
pub const SYCAMORE: Rgba<u8> = Rgba([154, 148, 49, 255]);
pub const TACAO: Rgba<u8> = Rgba([233, 183, 128, 255]);
pub const TACHA: Rgba<u8> = Rgba([212, 192, 100, 255]);
pub const TAMARIND: Rgba<u8> = Rgba([50, 15, 8, 255]);
pub const TAN: Rgba<u8> = Rgba([217, 174, 137, 255]);
pub const TAN_HIDE: Rgba<u8> = Rgba([248, 158, 92, 255]);
pub const TAUPE: Rgba<u8> = Rgba([73, 59, 50, 255]);
pub const THATCH_GREEN: Rgba<u8> = Rgba([65, 65, 35, 255]);
pub const THUNDER: Rgba<u8> = Rgba([52, 43, 45, 255]);
pub const THUNDERBIRD: Rgba<u8> = Rgba([192, 30, 30, 255]);
pub const TIARA: Rgba<u8> = Rgba([197, 216, 219, 255]);
pub const TOSCA: Rgba<u8> = Rgba([142, 66, 66, 255]);
pub const TREEHOUSE: Rgba<u8> = Rgba([51, 35, 27, 255]);
pub const TREE_POPPY: Rgba<u8> = Rgba([255, 162, 31, 255]);
pub const TROUT: Rgba<u8> = Rgba([78, 87, 99, 255]);
pub const TRUE_V: Rgba<u8> = Rgba([122, 116, 218, 255]);
pub const TUATARA: Rgba<u8> = Rgba([59, 59, 59, 255]);
pub const TUMBLEWEED: Rgba<u8> = Rgba([235, 166, 135, 255]);
pub const TUNA: Rgba<u8> = Rgba([55, 55, 73, 255]);
pub const TUNDORA: Rgba<u8> = Rgba([73, 70, 70, 255]);
pub const TURKISH_ROSE: Rgba<u8> = Rgba([175, 105, 128, 255]);
pub const TURMERIC: Rgba<u8> = Rgba([204, 181, 72, 255]);
pub const TUSSOCK: Rgba<u8> = Rgba([205, 153, 73, 255]);
pub const TWINE: Rgba<u8> = Rgba([190, 150, 92, 255]);
pub const ULTRAMARINE: Rgba<u8> = Rgba([39, 34, 180, 255]);
pub const VALENCIA: Rgba<u8> = Rgba([238, 85, 70, 255]);
pub const VENICE_BLUE: Rgba<u8> = Rgba([13, 88, 130, 255]);
pub const VERMILION: Rgba<u8> = Rgba([253, 62, 3, 255]);
pub const VESUVIUS: Rgba<u8> = Rgba([183, 75, 15, 255]);
pub const VIDA_LOCA: Rgba<u8> = Rgba([79, 128, 17, 255]);
pub const VIKING: Rgba<u8> = Rgba([97, 200, 225, 255]);
pub const VIOLA: Rgba<u8> = Rgba([205, 152, 186, 255]);
pub const VIOLET: Rgba<u8> = Rgba([38, 9, 66, 255]);
pub const VIOLET_EGGPLANT: Rgba<u8> = Rgba([174, 16, 176, 255]);
pub const VIRIDIAN: Rgba<u8> = Rgba([49, 134, 114, 255]);
pub const VIVID_TANGERINE: Rgba<u8> = Rgba([239, 141, 126, 255]);
pub const VIVID_VIOLET: Rgba<u8> = Rgba([121, 49, 134, 255]);
pub const VOODOO: Rgba<u8> = Rgba([107, 68, 99, 255]);
pub const WALNUT: Rgba<u8> = Rgba([117, 61, 25, 255]);
pub const WATERLOO: Rgba<u8> = Rgba([117, 125, 151, 255]);
pub const WATTLE: Rgba<u8> = Rgba([229, 212, 73, 255]);
pub const WELL_READ: Rgba<u8> = Rgba([192, 59, 59, 255]);
pub const WHITE: Rgba<u8> = Rgba([255, 255, 255, 255]);
pub const WILD_BLUE_YONDER: Rgba<u8> = Rgba([128, 133, 184, 255]);
pub const WILD_STRAWBERRY: Rgba<u8> = Rgba([255, 66, 152, 255]);
pub const WOODSMOKE: Rgba<u8> = Rgba([15, 15, 15, 255]);
pub const YELLOW: Rgba<u8> = Rgba([255, 255, 0, 112]);
pub const YELLOW_SEA: Rgba<u8> = Rgba([255, 172, 0, 240]);
pub const ZEST: Rgba<u8> = Rgba([227, 125, 22, 255]);
pub const ZEUS: Rgba<u8> = Rgba([39, 33, 26, 255]);
pub const ZIGGURAT: Rgba<u8> = Rgba([190, 223, 232, 255]);
pub const ZOMBIE: Rgba<u8> = Rgba([228, 219, 162, 255]);
pub const ZUCCINI: Rgba<u8> = Rgba([30, 80, 48, 255]);

lazy_static! {
  pub static ref BLOCKTYPE_COLOR_MAP: FnvHashMap<BlockType, Rgba<u8>> = {
    let mut blocktype_map = FnvHashMap::default();

    blocktype_map.insert(BlockType::Dirt, LEATHER);
    blocktype_map.insert(BlockType::Stone, GRAY);
    blocktype_map.insert(BlockType::Grass, MALACHITE);
    blocktype_map.insert(BlockType::Plants, EMERALD);
    blocktype_map.insert(BlockType::Torches, SCHOOL_BUS_YELLOW);
    blocktype_map.insert(BlockType::Trees, LEATHER);
    blocktype_map.insert(BlockType::Iron, BEAVER);
    blocktype_map.insert(BlockType::Copper, CUMIN);
    blocktype_map.insert(BlockType::Gold, SAHARA);
    blocktype_map.insert(BlockType::Silver, SUBMARINE);
    blocktype_map.insert(BlockType::ClosedDoor, PEAT);
    blocktype_map.insert(BlockType::OpenDoor, PEAT);
    blocktype_map.insert(BlockType::Heart, MAROON_FLUSH);
    blocktype_map.insert(BlockType::Bottles, SEAGULL);
    blocktype_map.insert(BlockType::Tables, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Chairs, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Anvils, SQUIRREL);
    blocktype_map.insert(BlockType::Furnaces, STACK);
    blocktype_map.insert(BlockType::WorkBenches, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Platforms, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Saplings, CAPE_PALLISER);
    blocktype_map.insert(BlockType::Containers, GOLDENROD);
    blocktype_map.insert(BlockType::Demonite, SCAMPI);
    blocktype_map.insert(BlockType::CorruptGrass, CHETWODE_BLUE);
    blocktype_map.insert(BlockType::CorruptPlants, TRUE_V);
    blocktype_map.insert(BlockType::Ebonstone, RUM);
    blocktype_map.insert(BlockType::DemonAltar, OLD_LAVENDER);
    blocktype_map.insert(BlockType::Sunflower, GOLD_TIPS);
    blocktype_map.insert(BlockType::Pots, COPPER_RUST);
    blocktype_map.insert(BlockType::PiggyBank, TURKISH_ROSE);
    blocktype_map.insert(BlockType::WoodBlock, CAPE_PALLISER);
    blocktype_map.insert(BlockType::ShadowOrbs, LAVENDER_PURPLE);
    blocktype_map.insert(BlockType::CorruptThorns, BLUE_BELL);
    blocktype_map.insert(BlockType::Candles, SCHOOL_BUS_YELLOW);
    blocktype_map.insert(BlockType::Chandeliers, TUMBLEWEED);
    blocktype_map.insert(BlockType::Jackolanterns, TIARA);
    blocktype_map.insert(BlockType::Presents, CARNATION);
    blocktype_map.insert(BlockType::Meteorite, DORADO);
    blocktype_map.insert(BlockType::GrayBrick, MOUNTAIN_MIST);
    blocktype_map.insert(BlockType::RedBrick, MEDIUM_CARMINE);
    blocktype_map.insert(BlockType::ClayBlock, IRONSTONE);
    blocktype_map.insert(BlockType::BlueDungeonBrick, FIORD);
    blocktype_map.insert(BlockType::HangingLanterns, KOURNIKOVA);
    blocktype_map.insert(BlockType::GreenDungeonBrick, AXOLOTL);
    blocktype_map.insert(BlockType::PinkDungeonBrick, VOODOO);
    blocktype_map.insert(BlockType::GoldBrick, SAHARA);
    blocktype_map.insert(BlockType::SilverBrick, SUBMARINE);
    blocktype_map.insert(BlockType::CopperBrick, CUMIN);
    blocktype_map.insert(BlockType::Spikes, GRAY);
    blocktype_map.insert(BlockType::WaterCandle, DODGER_BLUE);
    blocktype_map.insert(BlockType::Books, ROYAL_HEATH);
    blocktype_map.insert(BlockType::Cobweb, SUBMARINE);
    blocktype_map.insert(BlockType::Vines, APPLE);
    blocktype_map.insert(BlockType::Sand, BRIGHT_SUN);
    blocktype_map.insert(BlockType::Glass, ONAHAU);
    blocktype_map.insert(BlockType::SignVec, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Obsidian, PORT_GORE);
    blocktype_map.insert(BlockType::Ash, GRAVEL);
    blocktype_map.insert(BlockType::Hellstone, TOSCA);
    blocktype_map.insert(BlockType::Mud, DON_JUAN);
    blocktype_map.insert(BlockType::JungleGrass, ATLANTIS);
    blocktype_map.insert(BlockType::JunglePlants, ATLANTIS);
    blocktype_map.insert(BlockType::JungleVines, CHRISTI);
    blocktype_map.insert(BlockType::Sapphire, SHIP_COVE);
    blocktype_map.insert(BlockType::Ruby, CADILLAC);
    blocktype_map.insert(BlockType::Emerald, SEA_GREEN);
    blocktype_map.insert(BlockType::Topaz, DRIFTWOOD);
    blocktype_map.insert(BlockType::Amethyst, SEANCE);
    blocktype_map.insert(BlockType::Diamond, HALF_BAKED);
    blocktype_map.insert(BlockType::JungleThorns, TWINE);
    blocktype_map.insert(BlockType::MushroomGrass, AZURE_RADIANCE);
    blocktype_map.insert(BlockType::MushroomPlants, SORRELL_BROWN);
    blocktype_map.insert(BlockType::MushroomTrees, SORRELL_BROWN);
    blocktype_map.insert(BlockType::Plants2, EMERALD);
    blocktype_map.insert(BlockType::JunglePlants2, LIMA);
    blocktype_map.insert(BlockType::ObsidianBrick, SHARK);
    blocktype_map.insert(BlockType::HellstoneBrick, TOSCA);
    blocktype_map.insert(BlockType::Hellforge, VALENCIA);
    blocktype_map.insert(BlockType::ClayPot, SANDSTONE);
    blocktype_map.insert(BlockType::Beds, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Cactus, GREEN_LEAF);
    blocktype_map.insert(BlockType::Coral, PERSIAN_PINK);
    blocktype_map.insert(BlockType::ImmatureHerbs, FLAMENCO);
    blocktype_map.insert(BlockType::MatureHerbs, FLAMENCO);
    blocktype_map.insert(BlockType::BloomingHerbs, FLAMENCO);
    blocktype_map.insert(BlockType::Tombstones, SILVER);
    blocktype_map.insert(BlockType::Loom, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Pianos, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Dressers, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Benches, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Bathtubs, STACK);
    blocktype_map.insert(BlockType::Banners, VENICE_BLUE);
    blocktype_map.insert(BlockType::Lampposts, GEYSER);
    blocktype_map.insert(BlockType::Lamps, SCHOOL_BUS_YELLOW);
    blocktype_map.insert(BlockType::Kegs, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::ChineseLanterns, TREE_POPPY);
    blocktype_map.insert(BlockType::CookingPots, STACK);
    blocktype_map.insert(BlockType::Safes, STACK);
    blocktype_map.insert(BlockType::SkullLanterns, SCHOOL_BUS_YELLOW);
    blocktype_map.insert(BlockType::TrashCan, STACK);
    blocktype_map.insert(BlockType::Candelabras, SCHOOL_BUS_YELLOW);
    blocktype_map.insert(BlockType::Bookcases, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Thrones, WATTLE);
    blocktype_map.insert(BlockType::Bowls, LEATHER);
    blocktype_map.insert(BlockType::GrandfatherClocks, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Statues, STACK);
    blocktype_map.insert(BlockType::Sawmill, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Cobalt, ST_TROPAZ);
    blocktype_map.insert(BlockType::Mythril, BREAKER_BAY);
    blocktype_map.insert(BlockType::HallowedGrass, SEAGULL);
    blocktype_map.insert(BlockType::HallowedPlants, MOUNTAIN_MEADOW);
    blocktype_map.insert(BlockType::Adamantite, CLARET);
    blocktype_map.insert(BlockType::Ebonsand, DOLPHIN);
    blocktype_map.insert(BlockType::HallowedPlants2, SCOOTER);
    blocktype_map.insert(BlockType::TinkerersWorkbench, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::HallowedVines, PACIFIC_BLUE);
    blocktype_map.insert(BlockType::Pearlsand, BIZARRE);
    blocktype_map.insert(BlockType::Pearlstone, CHATELLE);
    blocktype_map.insert(BlockType::PearlstoneBrick, BIZARRE);
    blocktype_map.insert(BlockType::IridescentBrick, SALT_BOX);
    blocktype_map.insert(BlockType::Mudstone, DON_JUAN);
    blocktype_map.insert(BlockType::CobaltBrick, ST_TROPAZ);
    blocktype_map.insert(BlockType::MythrilBrick, BREAKER_BAY);
    blocktype_map.insert(BlockType::Silt, SHUTTLE_GRAY);
    blocktype_map.insert(BlockType::WoodenBeam, IROKO);
    blocktype_map.insert(BlockType::CrystalBall, PORTAGE);
    blocktype_map.insert(BlockType::DiscoBall, REGENT_ST_BLUE);
    blocktype_map.insert(BlockType::MagicalIceBlock, SEAGULL);
    blocktype_map.insert(BlockType::Mannequin, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Crystals, LAVENDER_MAGENTA);
    blocktype_map.insert(BlockType::ActiveStoneBlock, STAR_DUST);
    blocktype_map.insert(BlockType::InactiveStoneBlock, MINE_SHAFT);
    blocktype_map.insert(BlockType::Lever, STACK);
    blocktype_map.insert(BlockType::AdamantiteForge, ALIZARIN_CRIMSON);
    blocktype_map.insert(BlockType::MythrilAnvil, NORWAY);
    blocktype_map.insert(BlockType::PressurePlates, SUNGLO);
    blocktype_map.insert(BlockType::Switches, SWISS_COFFEE);
    blocktype_map.insert(BlockType::Traps, STACK);
    blocktype_map.insert(BlockType::Boulder, STORM_DUST);
    blocktype_map.insert(BlockType::MusicBoxes, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::DemoniteBrick, SCAMPI);
    blocktype_map.insert(BlockType::Explosives, WELL_READ);
    blocktype_map.insert(BlockType::InletPump, STACK);
    blocktype_map.insert(BlockType::OutletPump, STACK);
    blocktype_map.insert(BlockType::Timers, STACK);
    blocktype_map.insert(BlockType::CandyCaneBlock, THUNDERBIRD);
    blocktype_map.insert(BlockType::GreenCandyCaneBlock, MALACHITE);
    blocktype_map.insert(BlockType::SnowBlock, MABEL);
    blocktype_map.insert(BlockType::SnowBrick, JET_STREAM);
    blocktype_map.insert(BlockType::HolidayLights, CINNABAR);
    blocktype_map.insert(BlockType::AdamantiteBeam, CLARET);
    blocktype_map.insert(BlockType::SandstoneBrick, HUSK);
    blocktype_map.insert(BlockType::EbonstoneBrick, WILD_BLUE_YONDER);
    blocktype_map.insert(BlockType::RedStucco, VIVID_TANGERINE);
    blocktype_map.insert(BlockType::YellowStucco, HUSK);
    blocktype_map.insert(BlockType::GreenStucco, GRANNY_SMITH);
    blocktype_map.insert(BlockType::GrayStucco, BUD);
    blocktype_map.insert(BlockType::Ebonwood, DOLPHIN);
    blocktype_map.insert(BlockType::RichMahogany, AU_CHICO);
    blocktype_map.insert(BlockType::Pearlwood, CLAY_CREEK);
    blocktype_map.insert(BlockType::RainbowBrick, DARK_BLUE);
    blocktype_map.insert(BlockType::IceBlock, CORNFLOWER);
    blocktype_map.insert(BlockType::BreakableIce, SAIL);
    blocktype_map.insert(BlockType::CorruptIce, EAST_SIDE);
    blocktype_map.insert(BlockType::HallowedIce, MELANIE);
    blocktype_map.insert(BlockType::Stalactite, STORM_DUST);
    blocktype_map.insert(BlockType::Tin, CLAY_CREEK);
    blocktype_map.insert(BlockType::Lead, SAN_JUAN);
    blocktype_map.insert(BlockType::Tungsten, AMULET);
    blocktype_map.insert(BlockType::Platinum, ROCK_BLUE);
    blocktype_map.insert(BlockType::PineTree, ZOMBIE);
    blocktype_map.insert(BlockType::ChristmasTree, SEA_GREEN);
    blocktype_map.insert(BlockType::Sinks, CASPER);
    blocktype_map.insert(BlockType::PlatinumCandelabra, SCHOOL_BUS_YELLOW);
    blocktype_map.insert(BlockType::PlatinumCandle, SCHOOL_BUS_YELLOW);
    blocktype_map.insert(BlockType::TinBrick, CLAY_CREEK);
    blocktype_map.insert(BlockType::TungstenBrick, AMULET);
    blocktype_map.insert(BlockType::PlatinumBrick, ROCK_BLUE);
    blocktype_map.insert(BlockType::ExposedGems, MAGENTA_FUCHSIA);
    blocktype_map.insert(BlockType::GreenMoss, VIRIDIAN);
    blocktype_map.insert(BlockType::BrownMoss, PACIFIKA);
    blocktype_map.insert(BlockType::RedMoss, SANGUINE_BROWN);
    blocktype_map.insert(BlockType::BlueMoss, VENICE_BLUE);
    blocktype_map.insert(BlockType::PurpleMoss, VIVID_VIOLET);
    blocktype_map.insert(BlockType::LongMoss, STORM_DUST);
    blocktype_map.insert(BlockType::SmallPiles, GURKHA);
    blocktype_map.insert(BlockType::LargePiles, MAGENTA_FUCHSIA);
    blocktype_map.insert(BlockType::LargePiles2, MAGENTA_FUCHSIA);
    blocktype_map.insert(BlockType::CactusBlock, GREEN_LEAF);
    blocktype_map.insert(BlockType::Cloud, BABY_BLUE);
    blocktype_map.insert(BlockType::MushroomBlock, SORRELL_BROWN);
    blocktype_map.insert(BlockType::LivingWood, LEATHER);
    blocktype_map.insert(BlockType::LeafBlock, MALACHITE);
    blocktype_map.insert(BlockType::SlimeBlock, AZURE_RADIANCE);
    blocktype_map.insert(BlockType::BoneBlock, AVOCADO);
    blocktype_map.insert(BlockType::FleshBlock, MERLOT);
    blocktype_map.insert(BlockType::RainCloud, AMETHYST_SMOKE);
    blocktype_map.insert(BlockType::FrozenSlimeBlock, VIKING);
    blocktype_map.insert(BlockType::Asphalt, ARMADILLO);
    blocktype_map.insert(BlockType::FleshGrass, ROMAN);
    blocktype_map.insert(BlockType::FleshIce, PETITE_ORCHID);
    blocktype_map.insert(BlockType::FleshWeeds, FLUSH_MAHOGANY);
    blocktype_map.insert(BlockType::Sunplate, GALLIANO);
    blocktype_map.insert(BlockType::Crimstone, CROWN_OF_THORNS);
    blocktype_map.insert(BlockType::Crimtane, SOLID_PINK);
    blocktype_map.insert(BlockType::CrimsonVines, WELL_READ);
    blocktype_map.insert(BlockType::IceBrick, GLACIER);
    blocktype_map.insert(BlockType::WaterFountain, STACK);
    blocktype_map.insert(BlockType::Shadewood, SHUTTLE_GRAY);
    blocktype_map.insert(BlockType::Cannon, STACK);
    blocktype_map.insert(BlockType::LandMine, WELL_READ);
    blocktype_map.insert(BlockType::Chlorophyte, SULU);
    blocktype_map.insert(BlockType::SnowballLauncher, STACK);
    blocktype_map.insert(BlockType::Rope, PESTO);
    blocktype_map.insert(BlockType::Chain, STORM_DUST);
    blocktype_map.insert(BlockType::Campfire, FLAMENCO);
    blocktype_map.insert(BlockType::Firework, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Blendomatic, STACK);
    blocktype_map.insert(BlockType::MeatGrinder, STACK);
    blocktype_map.insert(BlockType::Extractinator, STACK);
    blocktype_map.insert(BlockType::Solidifier, STACK);
    blocktype_map.insert(BlockType::Palladium, FLAMINGO);
    blocktype_map.insert(BlockType::Orichalcum, BLUSH_PINK);
    blocktype_map.insert(BlockType::Titanium, FIORD);
    blocktype_map.insert(BlockType::Slush, SIROCCO);
    blocktype_map.insert(BlockType::Hive, ZEST);
    blocktype_map.insert(BlockType::LihzahrdBrick, OREGON);
    blocktype_map.insert(BlockType::DyePlants, WHITE);
    blocktype_map.insert(BlockType::DyeVat, STACK);
    blocktype_map.insert(BlockType::HoneyBlock, CALIFORNIA);
    blocktype_map.insert(BlockType::CrispyHoneyBlock, RUSTY_NAIL);
    blocktype_map.insert(BlockType::Larva, EQUATOR);
    blocktype_map.insert(BlockType::WoodenSpikes, AU_CHICO);
    blocktype_map.insert(BlockType::PlantDetritus, MAGENTA_FUCHSIA);
    blocktype_map.insert(BlockType::Crimsand, DUNE);
    blocktype_map.insert(BlockType::Teleporter, OLD_GOLD);
    blocktype_map.insert(BlockType::LifeFruit, CONIFER);
    blocktype_map.insert(BlockType::LihzahrdAltar, BROOM);
    blocktype_map.insert(BlockType::PlanteraBulb, LAVENDER_ROSE);
    blocktype_map.insert(BlockType::MetalBars, EQUATOR);
    blocktype_map.insert(BlockType::Painting3x3, JAMBALAYA);
    blocktype_map.insert(BlockType::Painting4x3, FUSCOUS_GRAY);
    blocktype_map.insert(BlockType::Painting6x4, JAMBALAYA);
    blocktype_map.insert(BlockType::ImbuingStation, PORTAGE);
    blocktype_map.insert(BlockType::BubbleMachine, ONAHAU);
    blocktype_map.insert(BlockType::Painting2x3, JAMBALAYA);
    blocktype_map.insert(BlockType::Painting3x2, JAMBALAYA);
    blocktype_map.insert(BlockType::Autohammer, OSLO_GRAY);
    blocktype_map.insert(BlockType::PalladiumColumn, PUNCH);
    blocktype_map.insert(BlockType::BubblegumBlock, MAGENTA_FUCHSIA);
    blocktype_map.insert(BlockType::Titanstone, ABBEY);
    blocktype_map.insert(BlockType::PumpkinBlock, DIXIE);
    blocktype_map.insert(BlockType::HayBlock, LUXOR_GOLD);
    blocktype_map.insert(BlockType::SpookyWood, PORT_GORE);
    blocktype_map.insert(BlockType::Pumpkins, TAN_HIDE);
    blocktype_map.insert(BlockType::AmethystGemsparkOff, ROYAL_PURPLE);
    blocktype_map.insert(BlockType::TopazGemsparkOff, SYCAMORE);
    blocktype_map.insert(BlockType::SapphireGemsparkOff, SMALT);
    blocktype_map.insert(BlockType::EmeraldGemsparkOff, CHATEAU_GREEN);
    blocktype_map.insert(BlockType::RubyGemsparkOff, NIGHT_SHADZ);
    blocktype_map.insert(BlockType::DiamondGemsparkOff, COMET);
    blocktype_map.insert(BlockType::AmberGemsparkOff, SEPIA_SKIN);
    blocktype_map.insert(BlockType::AmethystGemspark, PINK_FLAMINGO);
    blocktype_map.insert(BlockType::TopazGemspark, GOLDEN_FIZZ);
    blocktype_map.insert(BlockType::SapphireGemspark, BLUE_RIBBON);
    blocktype_map.insert(BlockType::EmeraldGemspark, SCREAMIN_GREEN);
    blocktype_map.insert(BlockType::RubyGemspark, SUNSET_ORANGE);
    blocktype_map.insert(BlockType::DiamondGemspark, ATHENS_GRAY);
    blocktype_map.insert(BlockType::AmberGemspark, JAFFA);
    blocktype_map.insert(BlockType::Womannequin, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::FireflyinaBottle, SPRAY);
    blocktype_map.insert(BlockType::LightningBuginaBottle, SPRAY);
    blocktype_map.insert(BlockType::Cog, PABLO);
    blocktype_map.insert(BlockType::StoneSlab, GRAY);
    blocktype_map.insert(BlockType::SandStoneSlab, HUSK);
    blocktype_map.insert(BlockType::BunnyCage, SPRAY);
    blocktype_map.insert(BlockType::SquirrelCage, SPRAY);
    blocktype_map.insert(BlockType::MallardDuckCage, SPRAY);
    blocktype_map.insert(BlockType::DuckCage, SPRAY);
    blocktype_map.insert(BlockType::BirdCage, SPRAY);
    blocktype_map.insert(BlockType::BlueJay, SPRAY);
    blocktype_map.insert(BlockType::CardinalCage, SPRAY);
    blocktype_map.insert(BlockType::FishBowl, SPRAY);
    blocktype_map.insert(BlockType::HeavyWorkBench, GRAY);
    blocktype_map.insert(BlockType::CopperPlating, CUMIN);
    blocktype_map.insert(BlockType::SnailCage, SPRAY);
    blocktype_map.insert(BlockType::GlowingSnailCage, SPRAY);
    blocktype_map.insert(BlockType::AmmoBox, VIDA_LOCA);
    blocktype_map.insert(BlockType::MonarchButterflyJar, SPRAY);
    blocktype_map.insert(BlockType::PurpleEmperorButterflyJar, SPRAY);
    blocktype_map.insert(BlockType::RedAdmiralButterflyJar, SPRAY);
    blocktype_map.insert(BlockType::UlyssesButterflyJar, SPRAY);
    blocktype_map.insert(BlockType::SulphurButterflyJar, SPRAY);
    blocktype_map.insert(BlockType::TreeNymphButterflyJar, SPRAY);
    blocktype_map.insert(BlockType::ZebraSwallowtailButterflyJar, SPRAY);
    blocktype_map.insert(BlockType::JuliaButterflyJar, SPRAY);
    blocktype_map.insert(BlockType::ScorpionCage, SPRAY);
    blocktype_map.insert(BlockType::BlackScorpionCage, SPRAY);
    blocktype_map.insert(BlockType::FrogCage, SPRAY);
    blocktype_map.insert(BlockType::MouseCage, SPRAY);
    blocktype_map.insert(BlockType::BoneWelder, STACK);
    blocktype_map.insert(BlockType::FleshCloningVat, STACK);
    blocktype_map.insert(BlockType::GlassKiln, STACK);
    blocktype_map.insert(BlockType::LihzahrdFurnace, STACK);
    blocktype_map.insert(BlockType::LivingLoom, STACK);
    blocktype_map.insert(BlockType::SkyMill, STACK);
    blocktype_map.insert(BlockType::IceMachine, STACK);
    blocktype_map.insert(BlockType::SteampunkBoiler, STACK);
    blocktype_map.insert(BlockType::HoneyDispenser, STACK);
    blocktype_map.insert(BlockType::PenguinCage, SPRAY);
    blocktype_map.insert(BlockType::WormCage, SPRAY);
    blocktype_map.insert(BlockType::DynastyWood, WALNUT);
    blocktype_map.insert(BlockType::RedDynastyShingles, CRAIL);
    blocktype_map.insert(BlockType::BlueDynastyShingles, BREAKER_BAY);
    blocktype_map.insert(BlockType::MinecartTrack, MONGOOSE);
    blocktype_map.insert(BlockType::Coralstone, BURNT_SIENNA);
    blocktype_map.insert(BlockType::BlueJellyfishBowl, SPRAY);
    blocktype_map.insert(BlockType::GreenJellyfishBowl, SPRAY);
    blocktype_map.insert(BlockType::PinkJellyfishBowl, SPRAY);
    blocktype_map.insert(BlockType::ShipInAbottle, QUINCY);
    blocktype_map.insert(BlockType::SeaweedPlanter, INDIAN_KHAKI);
    blocktype_map.insert(BlockType::BorealWood, KABUL);
    blocktype_map.insert(BlockType::PalmWood, HUSK);
    blocktype_map.insert(BlockType::PalmTree, DRIFTWOOD);
    blocktype_map.insert(BlockType::BeachPiles, HAMPTON);
    blocktype_map.insert(BlockType::TinPlating, CLAY_CREEK);
    blocktype_map.insert(BlockType::Waterfall, PERSIAN_BLUE);
    blocktype_map.insert(BlockType::Lavafall, SCARLET);
    blocktype_map.insert(BlockType::Confetti, ONAHAU);
    blocktype_map.insert(BlockType::ConfettiBlack, WOODSMOKE);
    blocktype_map.insert(BlockType::CopperCoinPile, BURNT_SIENNA);
    blocktype_map.insert(BlockType::SilverCoinPile, EDWARD);
    blocktype_map.insert(BlockType::GoldCoinPile, TURMERIC);
    blocktype_map.insert(BlockType::PlatinumCoinPile, ASH);
    blocktype_map.insert(BlockType::WeaponsRack, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::FireworksBox, TAN);
    blocktype_map.insert(BlockType::LivingFire, VERMILION);
    blocktype_map.insert(BlockType::AlphabetStatues, STACK);
    blocktype_map.insert(BlockType::FireworkFountain, MINT_GREEN);
    blocktype_map.insert(BlockType::GrasshopperCage, SPRAY);
    blocktype_map.insert(BlockType::LivingCursedFire, BRIGHT_GREEN);
    blocktype_map.insert(BlockType::LivingDemonFire, GOVERNOR_BAY);
    blocktype_map.insert(BlockType::LivingFrostFire, CYAN_AQUA);
    blocktype_map.insert(BlockType::LivingIchor, GOLDEN_TAINOI);
    blocktype_map.insert(BlockType::LivingUltrabrightFire, RIPTIDE);
    blocktype_map.insert(BlockType::Honeyfall, CALIFORNIA);
    blocktype_map.insert(BlockType::ChlorophyteBrick, CONIFER);
    blocktype_map.insert(BlockType::CrimtaneBrick, CARNATION);
    blocktype_map.insert(BlockType::ShroomitePlating, DARK_BLUE);
    blocktype_map.insert(BlockType::MushroomStatue, STACK);
    blocktype_map.insert(BlockType::MartianConduitPlating, SAN_MARINO);
    blocktype_map.insert(BlockType::ChimneySmoke, SHARK);
    blocktype_map.insert(BlockType::CrimtaneThorns, CARNATION);
    blocktype_map.insert(BlockType::VineRope, MALACHITE);
    blocktype_map.insert(BlockType::BewitchingTable, BEAVER);
    blocktype_map.insert(BlockType::AlchemyTable, BEAVER);
    blocktype_map.insert(BlockType::Sundial, GOLDEN_DREAM);
    blocktype_map.insert(BlockType::MarbleBlock, ROCK_BLUE);
    blocktype_map.insert(BlockType::GoldBirdCage, SPRAY);
    blocktype_map.insert(BlockType::GoldBunnyCage, SPRAY);
    blocktype_map.insert(BlockType::GoldButterflyCage, SPRAY);
    blocktype_map.insert(BlockType::GoldFrogCage, SPRAY);
    blocktype_map.insert(BlockType::GoldGrasshopperCage, SPRAY);
    blocktype_map.insert(BlockType::GoldMouseCage, SPRAY);
    blocktype_map.insert(BlockType::GoldWormCage, SPRAY);
    blocktype_map.insert(BlockType::SilkRope, DULL_LAVENDER);
    blocktype_map.insert(BlockType::WebRope, MYSTIC);
    blocktype_map.insert(BlockType::Marble, ROCK_BLUE);
    blocktype_map.insert(BlockType::Granite, JACARTA);
    blocktype_map.insert(BlockType::GraniteBlock, JACARTA);
    blocktype_map.insert(BlockType::MeteoriteBrick, CHETWODE_BLUE);
    blocktype_map.insert(BlockType::PinkSlimeBlock, HOT_PINK);
    blocktype_map.insert(BlockType::PeaceCandle, PERSIAN_PINK);
    blocktype_map.insert(BlockType::WaterDrip, PERSIAN_BLUE);
    blocktype_map.insert(BlockType::LavaDrip, SCARLET);
    blocktype_map.insert(BlockType::HoneyDrip, CALIFORNIA);
    blocktype_map.insert(BlockType::FishingCrate, LEATHER);
    blocktype_map.insert(BlockType::SharpeningStation, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::TargetDummy, LEATHER);
    blocktype_map.insert(BlockType::Bubble, CLASSIC_ROSE);
    blocktype_map.insert(BlockType::PlanterBox, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::LavaMoss, FLAMENCO);
    blocktype_map.insert(BlockType::VineFlowers, MALACHITE);
    blocktype_map.insert(BlockType::LivingMahogany, SEA_PINK);
    blocktype_map.insert(BlockType::LivingMahoganyLeaves, LIMA);
    blocktype_map.insert(BlockType::CrystalBlock, PIGMENT_INDIGO);
    blocktype_map.insert(BlockType::TrapdoorOpen, ROMAN_COFFEE);
    blocktype_map.insert(BlockType::TrapdoorClosed, ROMAN_COFFEE);
    blocktype_map.insert(BlockType::TallGateClosed, ROMAN_COFFEE);
    blocktype_map.insert(BlockType::TallGateOpen, ROMAN_COFFEE);
    blocktype_map.insert(BlockType::LavaLamp, SCARLET);
    blocktype_map.insert(BlockType::CageEnchantedNightcrawler, SPRAY);
    blocktype_map.insert(BlockType::CageBuggy, SPRAY);
    blocktype_map.insert(BlockType::CageGrubby, SPRAY);
    blocktype_map.insert(BlockType::CageSluggy, SPRAY);
    blocktype_map.insert(BlockType::ItemFrame, ANTIQUE_BRASS);
    blocktype_map.insert(BlockType::Sandstone, RAW_SIENNA);
    blocktype_map.insert(BlockType::HardenedSand, TACHA);
    blocktype_map.insert(BlockType::CorruptHardenedSand, KIMBERLY);
    blocktype_map.insert(BlockType::CrimsonHardenedSand, FUSCOUS_GRAY);
    blocktype_map.insert(BlockType::CorruptSandstone, BOSSANOVA);
    blocktype_map.insert(BlockType::CrimsonSandstone, ARMADILLO);
    blocktype_map.insert(BlockType::HallowHardenedSand, SPUN_PEARL);
    blocktype_map.insert(BlockType::HallowSandstone, VIOLA);
    blocktype_map.insert(BlockType::DesertFossil, POTTERS_CLAY);
    blocktype_map.insert(BlockType::Fireplace, GUNSMOKE);
    blocktype_map.insert(BlockType::Chimney, BOULDER);
    blocktype_map.insert(BlockType::FossilOre, GOLDEN_SAND);
    blocktype_map.insert(BlockType::LunarOre, FUSCOUS_GRAY);
    blocktype_map.insert(BlockType::LunarBrick, FUSCOUS_GRAY);
    blocktype_map.insert(BlockType::LunarMonolith, HORIZON);
    blocktype_map.insert(BlockType::Detonator, ALIZARIN_CRIMSON);
    blocktype_map.insert(BlockType::LunarCraftingStation, HORIZON);
    blocktype_map.insert(BlockType::SquirrelOrangeCage, SPRAY);
    blocktype_map.insert(BlockType::SquirrelGoldCage, SPRAY);
    blocktype_map.insert(BlockType::LunarBlockSolar, VERMILION);
    blocktype_map.insert(BlockType::LunarBlockVortex, EASTERN_BLUE);
    blocktype_map.insert(BlockType::LunarBlockNebula, PURPLE_HEART);
    blocktype_map.insert(BlockType::LunarBlockStardust, CURIOUS_BLUE);
    blocktype_map.insert(BlockType::LogicGateLamp, WATERLOO);
    blocktype_map.insert(BlockType::LogicGate, WHITE);
    blocktype_map.insert(BlockType::ConveyorBeltLeft, TUNDORA);
    blocktype_map.insert(BlockType::ConveyorBeltRight, TUNDORA);
    blocktype_map.insert(BlockType::LogicSensor, WHITE);
    blocktype_map.insert(BlockType::WirePipe, POLO_BLUE);
    blocktype_map.insert(BlockType::AnnouncementBox, CASPER);
    blocktype_map.insert(BlockType::TeamBlockRed, CASTRO);
    blocktype_map.insert(BlockType::TeamBlockRedPlatform, CLARET);
    blocktype_map.insert(BlockType::WeightedPressurePlate, WHITE);
    blocktype_map.insert(BlockType::WireBulb, MASALA);
    blocktype_map.insert(BlockType::TeamBlockGreen, JEWEL);
    blocktype_map.insert(BlockType::TeamBlockBlue, ASTRONAUT);
    blocktype_map.insert(BlockType::TeamBlockYellow, SEPIA);
    blocktype_map.insert(BlockType::TeamBlockPink, METEORITE);
    blocktype_map.insert(BlockType::TeamBlockWhite, COMET);
    blocktype_map.insert(BlockType::TeamBlockGreenPlatform, CHATEAU_GREEN);
    blocktype_map.insert(BlockType::TeamBlockBluePlatform, AZURE);
    blocktype_map.insert(BlockType::TeamBlockYellowPlatform, MANDALAY);
    blocktype_map.insert(BlockType::TeamBlockPinkPlatform, PURPLE);
    blocktype_map.insert(BlockType::TeamBlockWhitePlatform, AMETHYST_SMOKE);
    blocktype_map.insert(BlockType::GemLocks, WHITE);
    blocktype_map.insert(BlockType::FakeContainers, WHITE);
    blocktype_map.insert(BlockType::ProjectilePressurePad, CURIOUS_BLUE);
    blocktype_map.insert(BlockType::GeyserTrap, BOULDER);
    blocktype_map.insert(BlockType::BeeHive, STRAW);
    blocktype_map.insert(BlockType::PixelBox, TUNA);
    blocktype_map.insert(BlockType::SillyBalloonPink, WILD_STRAWBERRY);
    blocktype_map.insert(BlockType::SillyBalloonPurple, MEDIUM_PURPLE);
    blocktype_map.insert(BlockType::SillyBalloonGreen, PUERTO_RICO);
    blocktype_map.insert(BlockType::SillyStreamerBlue, PICTON_BLUE);
    blocktype_map.insert(BlockType::SillyStreamerGreen, SCREAMIN_GREEN);
    blocktype_map.insert(BlockType::SillyStreamerPink, FRENCH_ROSE);
    blocktype_map.insert(BlockType::SillyBalloonMachine, MAUVELOUS);
    blocktype_map.insert(BlockType::SillyBalloonTile, WHITE);
    blocktype_map.insert(BlockType::Pigronata, VIOLET_EGGPLANT);
    blocktype_map.insert(BlockType::PartyMonolith, SPRING_GREEN);
    blocktype_map.insert(BlockType::PartyBundleOfBalloonTile, MEDIUM_PURPLE);
    blocktype_map.insert(BlockType::PartyPresent, WHITE);
    blocktype_map.insert(BlockType::SandFallBlock, CHENIN);
    blocktype_map.insert(BlockType::SnowFallBlock, ZIGGURAT);
    blocktype_map.insert(BlockType::SnowCloud, BALI_HAI);
    blocktype_map.insert(BlockType::SandDrip, DANDELION);
    blocktype_map.insert(BlockType::DjinnLamp, GALLIANO);
    blocktype_map.insert(BlockType::DefendersForge, CORNFLOWER);
    blocktype_map.insert(BlockType::WarTable, TACAO);
    blocktype_map.insert(BlockType::WarTableBanner, CERULEAN_BLUE);
    blocktype_map.insert(BlockType::ElderCrystalStand, TUSSOCK);
    blocktype_map.insert(BlockType::Containers2, GOLDENROD);
    blocktype_map.insert(BlockType::FakeContainers2, WHITE);
    blocktype_map.insert(BlockType::Tables2, ANTIQUE_BRASS);
    blocktype_map
  };
  pub static ref WALLTYPE_COLOR_MAP: FnvHashMap<WallType, Rgba<u8>> = {
    let mut walltype_map = FnvHashMap::default();

    walltype_map.insert(WallType::Stone, MINE_SHAFT);
    walltype_map.insert(WallType::DirtUnsafe, MILLBROOK);
    walltype_map.insert(WallType::EbonstoneUnsafe, GUN_POWDER);
    walltype_map.insert(WallType::Wood, IROKO);
    walltype_map.insert(WallType::GrayBrick, MINE_SHAFT);
    walltype_map.insert(WallType::RedBrick, HEATH);
    walltype_map.insert(WallType::BlueDungeonUnsafe, MIRAGE);
    walltype_map.insert(WallType::GreenDungeonUnsafe, LOG_CABIN);
    walltype_map.insert(WallType::PinkDungeonUnsafe, BASTILLE);
    walltype_map.insert(WallType::GoldBrick, BRONZETONE);
    walltype_map.insert(WallType::SilverBrick, OUTER_SPACE);
    walltype_map.insert(WallType::CopperBrick, MOROCCO_BROWN);
    walltype_map.insert(WallType::HellstoneBrickUnsafe, CRATER_BROWN);
    walltype_map.insert(WallType::ObsidianBrickUnsafe, WOODSMOKE);
    walltype_map.insert(WallType::MudUnsafe, THUNDER);
    walltype_map.insert(WallType::Dirt, MILLBROOK);
    walltype_map.insert(WallType::BlueDungeon, MIRAGE);
    walltype_map.insert(WallType::GreenDungeon, LOG_CABIN);
    walltype_map.insert(WallType::PinkDungeon, BASTILLE);
    walltype_map.insert(WallType::ObsidianBrick, WOODSMOKE);
    walltype_map.insert(WallType::Glass, BLACK);
    walltype_map.insert(WallType::PearlstoneBrick, SCORPION);
    walltype_map.insert(WallType::IridescentBrick, SHARK);
    walltype_map.insert(WallType::MudstoneBrick, THUNDER);
    walltype_map.insert(WallType::CobaltBrick, BIG_STONE);
    walltype_map.insert(WallType::MythrilBrick, BLUE_DIANNE);
    walltype_map.insert(WallType::Planked, MILLBROOK);
    walltype_map.insert(WallType::PearlstoneBrickUnsafe, SCARPA_FLOW);
    walltype_map.insert(WallType::CandyCane, HEATH);
    walltype_map.insert(WallType::GreenCandyCane, CAMARONE);
    walltype_map.insert(WallType::SnowBrick, TROUT);
    walltype_map.insert(WallType::AdamantiteBeam, CASTRO);
    walltype_map.insert(WallType::DemoniteBrick, MARTINIQUE);
    walltype_map.insert(WallType::SandstoneBrick, LISBON_BROWN);
    walltype_map.insert(WallType::EbonstoneBrick, TUNA);
    walltype_map.insert(WallType::RedStucco, CONGO_BROWN);
    walltype_map.insert(WallType::YellowStucco, LISBON_BROWN);
    walltype_map.insert(WallType::GreenStucco, HEAVY_METAL);
    walltype_map.insert(WallType::Gray, FUSCOUS_GRAY);
    walltype_map.insert(WallType::SnowWallUnsafe, CORDUROY);
    walltype_map.insert(WallType::Ebonwood, TUNA);
    walltype_map.insert(WallType::RichMaogany, CRATER_BROWN);
    walltype_map.insert(WallType::Pearlwood, MONDO);
    walltype_map.insert(WallType::RainbowBrick, MINE_SHAFT);
    walltype_map.insert(WallType::TinBrick, ARMADILLO);
    walltype_map.insert(WallType::TungstenBrick, HEAVY_METAL);
    walltype_map.insert(WallType::PlatinumBrick, ABBEY);
    walltype_map.insert(WallType::AmethystUnsafe, MINE_SHAFT);
    walltype_map.insert(WallType::TopazUnsafe, MINE_SHAFT);
    walltype_map.insert(WallType::SapphireUnsafe, MINE_SHAFT);
    walltype_map.insert(WallType::EmeraldUnsafe, MINE_SHAFT);
    walltype_map.insert(WallType::RubyUnsafe, MINE_SHAFT);
    walltype_map.insert(WallType::DiamondUnsafe, MINE_SHAFT);
    walltype_map.insert(WallType::CaveUnsafe, HEAVY_METAL);
    walltype_map.insert(WallType::Cave2unsafe, RANGITOTO);
    walltype_map.insert(WallType::Cave3unsafe, COCOA_BROWN);
    walltype_map.insert(WallType::Cave4unsafe, SHARK);
    walltype_map.insert(WallType::Cave5unsafe, BLEACHED_CEDAR);
    walltype_map.insert(WallType::Cave6unsafe, MILLBROOK);
    walltype_map.insert(WallType::LivingLeaf, COUNTY_GREEN);
    walltype_map.insert(WallType::Cave7unsafe, BISTRE);
    walltype_map.insert(WallType::SpiderUnsafe, ZEUS);
    walltype_map.insert(WallType::GrassUnsafe, ZUCCINI);
    walltype_map.insert(WallType::JungleUnsafe, CLOVER);
    walltype_map.insert(WallType::FlowerUnsafe, ZUCCINI);
    walltype_map.insert(WallType::Grass, ZUCCINI);
    walltype_map.insert(WallType::Jungle, CLOVER);
    walltype_map.insert(WallType::Flower, ZUCCINI);
    walltype_map.insert(WallType::CorruptGrassUnsafe, EBONY_CLAY);
    walltype_map.insert(WallType::HallowedGrassUnsafe, BLUE_DIANNE);
    walltype_map.insert(WallType::IceUnsafe, KASHMIR_BLUE);
    walltype_map.insert(WallType::Cactus, GREEN_HOUSE);
    walltype_map.insert(WallType::Cloud, PERIWINKLE_GRAY);
    walltype_map.insert(WallType::Mushroom, GUN_POWDER);
    walltype_map.insert(WallType::Bone, THATCH_GREEN);
    walltype_map.insert(WallType::Slime, MADISON);
    walltype_map.insert(WallType::Flesh, AUBERGINE);
    walltype_map.insert(WallType::LivingWood, CORK);
    walltype_map.insert(WallType::ObsidianBackUnsafe, BISCAY);
    walltype_map.insert(WallType::MushroomUnsafe, GUN_POWDER);
    walltype_map.insert(WallType::CrimsonGrassUnsafe, BUCCANEER);
    walltype_map.insert(WallType::DiscWall, METALLIC_BRONZE);
    walltype_map.insert(WallType::CrimstoneUnsafe, JON);
    walltype_map.insert(WallType::IceBrick, BLUE_DIANNE);
    walltype_map.insert(WallType::Shadewood, OUTER_SPACE);
    walltype_map.insert(WallType::HiveUnsafe, RUSSET);
    walltype_map.insert(WallType::LihzahrdBrickUnsafe, TAMARIND);
    walltype_map.insert(WallType::PurpleStainedGlass, BLACK);
    walltype_map.insert(WallType::YellowStainedGlass, BLACK);
    walltype_map.insert(WallType::BlueStainedGlass, BLACK);
    walltype_map.insert(WallType::GreenStainedGlass, BLACK);
    walltype_map.insert(WallType::RedStainedGlass, BLACK);
    walltype_map.insert(WallType::RainbowStainedGlass, BLACK);
    walltype_map.insert(WallType::BlueDungeonSlabUnsafe, SHARK);
    walltype_map.insert(WallType::BlueDungeonTileUnsafe, BALTIC_SEA);
    walltype_map.insert(WallType::PinkDungeonSlabUnsafe, VOODOO);
    walltype_map.insert(WallType::PinkDungeonTileUnsafe, EGGPLANT);
    walltype_map.insert(WallType::GreenDungeonSlabUnsafe, MINE_SHAFT);
    walltype_map.insert(WallType::GreenDungeonTileUnsafe, OUTER_SPACE);
    walltype_map.insert(WallType::BlueDungeonSlab, SHARK);
    walltype_map.insert(WallType::BlueDungeonTile, BALTIC_SEA);
    walltype_map.insert(WallType::PinkDungeonSlab, VOODOO);
    walltype_map.insert(WallType::PinkDungeonTile, EGGPLANT);
    walltype_map.insert(WallType::GreenDungeonSlab, MINE_SHAFT);
    walltype_map.insert(WallType::GreenDungeonTile, OUTER_SPACE);
    walltype_map.insert(WallType::WoodenFence, BLACK);
    walltype_map.insert(WallType::MetalFence, BLACK);
    walltype_map.insert(WallType::Hive, RUSSET);
    walltype_map.insert(WallType::PalladiumColumn, CHERRYWOOD);
    walltype_map.insert(WallType::BubblegumBlock, PLUM);
    walltype_map.insert(WallType::TitanstoneBlock, TREEHOUSE);
    walltype_map.insert(WallType::LihzahrdBrick, TAMARIND);
    walltype_map.insert(WallType::Pumpkin, PERU_TAN);
    walltype_map.insert(WallType::Hay, MADRAS);
    walltype_map.insert(WallType::SpookyWood, SHARK);
    walltype_map.insert(WallType::ChristmasTreeWallpaper, HEATH);
    walltype_map.insert(WallType::OrnamentWallpaper, FRIAR_GRAY);
    walltype_map.insert(WallType::CandyCaneWallpaper, COUNTY_GREEN);
    walltype_map.insert(WallType::FestiveWallpaper, HEATH);
    walltype_map.insert(WallType::StarsWallpaper, BLUE_ZODIAC);
    walltype_map.insert(WallType::SquigglesWallpaper, INDIAN_KHAKI);
    walltype_map.insert(WallType::SnowflakeWallpaper, STORM_GRAY);
    walltype_map.insert(WallType::KrampusHornWallpaper, HACIENDA);
    walltype_map.insert(WallType::BluegreenWallpaper, DARK_FERN);
    walltype_map.insert(WallType::GrinchFingerWallpaper, DINGLEY);
    walltype_map.insert(WallType::FancyGrayWallpaper, SHUTTLE_GRAY);
    walltype_map.insert(WallType::IceFloeWallpaper, MARINER);
    walltype_map.insert(WallType::MusicWallpaper, CLAIRVOYANT);
    walltype_map.insert(WallType::PurpleRainWallpaper, DAISY_BUSH);
    walltype_map.insert(WallType::RainbowWallpaper, ULTRAMARINE);
    walltype_map.insert(WallType::SparkleStoneWallpaper, COMET);
    walltype_map.insert(WallType::StarlitHeavenWallpaper, COD_GRAY);
    walltype_map.insert(WallType::BubbleWallpaper, GOVERNOR_BAY);
    walltype_map.insert(WallType::CopperPipeWallpaper, RED_BEECH);
    walltype_map.insert(WallType::DuckyWallpaper, DEEP_CERULEAN);
    walltype_map.insert(WallType::Waterfall, ST_TROPAZ);
    walltype_map.insert(WallType::Lavafall, VESUVIUS);
    walltype_map.insert(WallType::EbonwoodFence, SCARPA_FLOW);
    walltype_map.insert(WallType::RichMahoganyFence, BUCCANEER);
    walltype_map.insert(WallType::PearlwoodFence, GO_BEN);
    walltype_map.insert(WallType::ShadewoodFence, CAPE_COD);
    walltype_map.insert(WallType::WhiteDynasty, JUNGLE_GREEN);
    walltype_map.insert(WallType::BlueDynasty, CORDUROY);
    walltype_map.insert(WallType::ArcaneRunes, GRAPE);
    walltype_map.insert(WallType::IronFence, BLACK);
    walltype_map.insert(WallType::CopperPlating, COPPER_CANYON);
    walltype_map.insert(WallType::StoneSlab, TUATARA);
    walltype_map.insert(WallType::Sail, ZOMBIE);
    walltype_map.insert(WallType::BorealWood, TAUPE);
    walltype_map.insert(WallType::BorealWoodFence, BLACK);
    walltype_map.insert(WallType::PalmWood, DALLAS);
    walltype_map.insert(WallType::PalmWoodFence, BLACK);
    walltype_map.insert(WallType::AmberGemspark, JAFFA);
    walltype_map.insert(WallType::AmethystGemspark, PINK_FLAMINGO);
    walltype_map.insert(WallType::DiamondGemspark, ATHENS_GRAY);
    walltype_map.insert(WallType::EmeraldGemspark, SCREAMIN_GREEN);
    walltype_map.insert(WallType::AmberGemsparkOff, SEPIA_SKIN);
    walltype_map.insert(WallType::AmethystGemsparkOff, ROYAL_PURPLE);
    walltype_map.insert(WallType::DiamondGemsparkOff, COMET);
    walltype_map.insert(WallType::EmeraldGemsparkOff, CHATEAU_GREEN);
    walltype_map.insert(WallType::RubyGemsparkOff, NIGHT_SHADZ);
    walltype_map.insert(WallType::SapphireGemsparkOff, SMALT);
    walltype_map.insert(WallType::TopazGemsparkOff, SYCAMORE);
    walltype_map.insert(WallType::RubyGemspark, SUNSET_ORANGE);
    walltype_map.insert(WallType::SapphireGemspark, BLUE_RIBBON);
    walltype_map.insert(WallType::TopazGemspark, GOLDEN_FIZZ);
    walltype_map.insert(WallType::TinPlating, KELP);
    walltype_map.insert(WallType::Confetti, BLACK);
    walltype_map.insert(WallType::ConfettiBlack, BLACK);
    walltype_map.insert(WallType::CaveWall, BLACK_MARLIN);
    walltype_map.insert(WallType::CaveWall2, BLACK_MARLIN);
    walltype_map.insert(WallType::Honeyfall, RENO_SAND);
    walltype_map.insert(WallType::ChlorophyteBrick, VIDA_LOCA);
    walltype_map.insert(WallType::CrimtaneBrick, BLACK_ROSE);
    walltype_map.insert(WallType::ShroomitePlating, DARK_BLUE);
    walltype_map.insert(WallType::MartianConduit, GUN_POWDER);
    walltype_map.insert(WallType::HellstoneBrick, JON);
    walltype_map.insert(WallType::MarbleUnsafe, STORM_GRAY);
    walltype_map.insert(WallType::MarbleBlock, STORM_GRAY);
    walltype_map.insert(WallType::GraniteUnsafe, HAITI);
    walltype_map.insert(WallType::GraniteBlock, HAITI);
    walltype_map.insert(WallType::MeteoriteBrick, EAST_BAY);
    walltype_map.insert(WallType::Marble, STORM_GRAY);
    walltype_map.insert(WallType::Granite, HAITI);
    walltype_map.insert(WallType::Cave8unsafe, MINE_SHAFT);
    walltype_map.insert(WallType::Crystal, VIOLET);
    walltype_map.insert(WallType::Sandstone, MULE_FAWN);
    walltype_map.insert(WallType::CorruptionUnsafe1, MORTAR);
    walltype_map.insert(WallType::CorruptionUnsafe2, BRIGHT_GRAY);
    walltype_map.insert(WallType::CorruptionUnsafe3, GUN_POWDER);
    walltype_map.insert(WallType::CorruptionUnsafe4, VOODOO);
    walltype_map.insert(WallType::CrimsonUnsafe1, EL_SALVA);
    walltype_map.insert(WallType::CrimsonUnsafe2, STILETTO);
    walltype_map.insert(WallType::CrimsonUnsafe3, PERSIAN_PLUM);
    walltype_map.insert(WallType::CrimsonUnsafe4, STILETTO);
    walltype_map.insert(WallType::DirtUnsafe1, QUINCY);
    walltype_map.insert(WallType::DirtUnsafe2, ROMAN_COFFEE);
    walltype_map.insert(WallType::DirtUnsafe3, MILLBROOK);
    walltype_map.insert(WallType::DirtUnsafe4, ROMAN_COFFEE);
    walltype_map.insert(WallType::HallowUnsafe1, PLUM);
    walltype_map.insert(WallType::HallowUnsafe2, MAMBA);
    walltype_map.insert(WallType::HallowUnsafe3, CRANBERRY);
    walltype_map.insert(WallType::HallowUnsafe4, AFFAIR);
    walltype_map.insert(WallType::JungleUnsafe1, ARMADILLO);
    walltype_map.insert(WallType::JungleUnsafe2, CABBAGE_PONT);
    walltype_map.insert(WallType::JungleUnsafe3, COUNTY_GREEN);
    walltype_map.insert(WallType::JungleUnsafe4, AXOLOTL);
    walltype_map.insert(WallType::LavaUnsafe1, SHARK);
    walltype_map.insert(WallType::LavaUnsafe2, TUNDORA);
    walltype_map.insert(WallType::LavaUnsafe3, LONESTAR);
    walltype_map.insert(WallType::LavaUnsafe4, KABUL);
    walltype_map.insert(WallType::RocksUnsafe1, FUSCOUS_GRAY);
    walltype_map.insert(WallType::RocksUnsafe2, CAPE_COD);
    walltype_map.insert(WallType::RocksUnsafe3, MATTERHORN);
    walltype_map.insert(WallType::RocksUnsafe4, LIVID_BROWN);
    walltype_map.insert(WallType::HardenedSand, CAPE_PALLISER);
    walltype_map.insert(WallType::CorruptHardenedSand, MARTINIQUE);
    walltype_map.insert(WallType::CrimsonHardenedSand, AUBERGINE);
    walltype_map.insert(WallType::HallowHardenedSand, BUTTERFLY_BUSH);
    walltype_map.insert(WallType::CorruptSandstone, MARTINIQUE);
    walltype_map.insert(WallType::CrimsonSandstone, CORK);
    walltype_map.insert(WallType::HallowSandstone, VOODOO);
    walltype_map.insert(WallType::DesertFossil, CEDAR);
    walltype_map.insert(WallType::LunarBrickWall, DUNE);
    walltype_map.insert(WallType::CogWall, CAPE_COD);
    walltype_map.insert(WallType::SandFall, PESTO);
    walltype_map.insert(WallType::SnowFall, DANUBE);
    walltype_map.insert(WallType::SillyBalloonPinkWall, JAZZBERRY_JAM);
    walltype_map.insert(WallType::SillyBalloonPurpleWall, ROYAL_PURPLE);
    walltype_map.insert(WallType::SillyBalloonGreenWall, PINE_GREEN);
    walltype_map
  };
  pub static ref PAINT_COLOR_MAP: FnvHashMap<u8, Rgba<u8>> = {
    let mut paint_map = FnvHashMap::default();
    paint_map.insert(0, BLACK);
    paint_map.insert(1, RED);
    paint_map.insert(2, FLUSH_ORANGE);
    paint_map.insert(3, YELLOW);
    paint_map.insert(4, CHARTREUSE);
    paint_map.insert(5, GREEN);
    paint_map.insert(6, SPRING_GREEN);
    paint_map.insert(7, CYAN_AQUA);
    paint_map.insert(8, AZURE_RADIANCE);
    paint_map.insert(9, BLUE);
    paint_map.insert(10, ELECTRIC_VIOLET);
    paint_map.insert(11, MAGENTA_FUCHSIA);
    paint_map.insert(12, ROSE);
    paint_map.insert(13, RED);
    paint_map.insert(14, FLUSH_ORANGE);
    paint_map.insert(15, YELLOW);
    paint_map.insert(16, CHARTREUSE);
    paint_map.insert(17, GREEN);
    paint_map.insert(18, SPRING_GREEN);
    paint_map.insert(19, CYAN_AQUA);
    paint_map.insert(20, AZURE_RADIANCE);
    paint_map.insert(21, BLUE);
    paint_map.insert(22, ELECTRIC_VIOLET);
    paint_map.insert(23, MAGENTA_FUCHSIA);
    paint_map.insert(24, ROSE);
    paint_map.insert(25, ABBEY);
    paint_map.insert(26, WHITE);
    paint_map.insert(27, SILVER_CHALICE);
    paint_map.insert(28, MACARONI_AND_CHEESE);
    paint_map.insert(29, WOODSMOKE);
    paint_map.insert(30, SILVER_SAND);
    paint_map
  };
}

pub const SPACE_COLOR: Rgba<u8> = MATISSE;
pub const SKY_COLOR: Rgba<u8> = MALIBU;
pub const UNDERGROUND_COLOR: Rgba<u8> = SADDLE;
pub const CAVERN_COLOR: Rgba<u8> = ARMADILLO;
pub const HELL_COLOR: Rgba<u8> = CHOCOLATE;
pub const LAVA_COLOR: Rgba<u8> = SCARLET;
pub const HONEY_COLOR: Rgba<u8> = YELLOW_SEA;
pub const WATER_COLOR: Rgba<u8> = BLUE;
pub const RED_WIRE_COLOR: Rgba<u8> = RED;
pub const BLUE_WIRE_COLOR: Rgba<u8> = BLUE;
pub const GREEN_WIRE_COLOR: Rgba<u8> = GREEN;
pub const YELLOW_WIRE_COLOR: Rgba<u8> = YELLOW;
